lib/src/message_input.dart
Wrapped the TextField in a LimitedBox, gave the MessageInput a new property for that which defaults to 150p
Attached screenshots of before and after:
BEFORE:
AFTER:
=> fix for #12

lib/src/message_widget.dart
Added User's name on the timestamp for the message_widget as advertised on the [website](https://getstream.io/chat/flutter/tutorial/)
Android:
iOS:
=> MessageWidget now has user's name in the timestamp (like advertised design)

lib/src/message_list_view.dart, lib/src/message_widget.dart, lib/src/user_avatar.dart
Added onUserAvatarTap for MessageWidget and MessagesListView
=> Added onUserAvatarTap

lib/src/message_list_view.dart
- [x ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ x] The code changes follow best practices
Most chat apps have a notion of the keyboard dismissing when the user pulls down on the chat. Added the property to MessageListView and forward that to the ListView that's created inside
=> Expose ScrollViewKeyboardDismissBehavior to LIstView

lib/src/full_screen_image.dart
Add back button to the full-screen view to help ios users exit it using a button instead of swiping (it's not so obvious)
=> add back button

CHANGELOG.md, pubspec.yaml
=> version bump

lib/src/channel_list_view.dart
The widget `ChannelListView` allows for various levels of customization through builders. Notably, it does not allow a user to customize messages or layouts for empty channels. 
This PR adds a new builder `emptyBuilder` to handle instances where a channel list might be empty. This builder can be null and in instances where this is true, it defaults to the pre-configured error message previously shown.
=> Expose builder for empty channel state

lib/src/channel_list_view.dart, lib/src/message_input.dart
The input text style and icon used as part of `MessageInput` are not configurable in the constructor or via `StreamChatTheme`. 
This PR adds two additional options to `MessageInput`. 
- `inputTextStyle`: Text style used in message text field. If null, `MessageInput` uses `Theme.of(context).textTheme.bodyText2`.
- `attachmentIconColor`: Color used for the attachment icon. 
- Remove `Colors.transparency` in favor of `MaterialType.transparency`. 
PR #135 should be merged first.
=> Expose addition input styling options

packages/dart_client/lib/src/client.dart, packages/dart_client/test/src/client_test.dart, packages/flutter_widgets/example/lib/notifications_service.dart
- Replace push provider string with an enum. 
- Add document for added public API surface
=> [Dart-LLC] Create enum for Push Providers 

packages/stream_chat_flutter/lib/src/channel_list_view.dart
As reported:  "When we use ChannelListView and we override the onImageTap trying to push our own view, it throws an error. `onImageTap` is called when the widget is building."
Add lambda which calls `widget.onImageTap` when pressed.
=> fix: Method being called during build

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/version.dart, packages/stream_chat/pubspec.yaml, packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_list_view.dart, packages/stream_chat_flutter/lib/src/user_list_view.dart, packages/stream_chat_flutter/pubspec.yaml, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/message_list_core.dart, packages/stream_chat_flutter_core/lib/src/user_list_core.dart, packages/stream_chat_flutter_core/pubspec.yaml, packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/pubspec.yaml
🛑️ Breaking Changes from `2.0.0-nullsafety.6`
- `ConnectUserWithProvider` now requires `tokenProvider` as a required param. (Removed from the constructor)
- `client.disconnect()` is now divided into two different functions
- `client.closeConnection()` -> for closing user websocket connection.
- `client.disconnectUser()` -> for disconnecting user and resetting client state.
- `client.devToken()` now returns a `Token` model instead of `String`.
- `ApiError` is removed in favor of `StreamChatError`
- `StreamChatError` -> parent type for all the stream errors.
- `StreamWebSocketError` -> for user websocket related errors.
- `StreamChatNetworkError` -> for network related errors.
- `client.queryChannels()`, `channel.query()` options param is removed in favor of individual params
- …
=> chore: v2.0.0 nullsafety.8

packages/stream_chat_flutter_core/lib/src/stream_chat_core.dart, packages/stream_chat_flutter_core/test/stream_chat_core_test.dart
we used `AppLifecycleState.resumed` as the only foreground state
that caused the client to disconnect in certain situations (for example system dialogs)
this should fix #524
=> fix: use inactive as a foreground state

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/stream_chat_theme.dart, packages/stream_chat_flutter/lib/src/user_avatar.dart
This PR adds a placeholder widget builder for the UserAvatar. It is present in `StreamChatTheme` and is used in `UserAvatar`'s `CachedNetworkImage`.
Fixes #516
=> feat(ui): add UserAvatar placeholder builder to theme and widget

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/channel_header.dart, packages/stream_chat_flutter/lib/src/channel_list_header.dart, packages/stream_chat_flutter/lib/src/gallery_footer.dart, packages/stream_chat_flutter/lib/src/gallery_header.dart, packages/stream_chat_flutter/lib/src/thread_header.dart
This PR adds the `backgroundColor` property to the various header, footer widgets.
=> feat(ui): added backgroundColor property to the various header, footer widgets

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/test/src/api/channel_test.dart, packages/stream_chat/test/src/core/models/reaction_test.dart, packages/stream_chat_flutter/test/src/channel_image_test.dart, packages/stream_chat_flutter_core/example/lib/main.dart
This will add shortcuts to get, set and update the name and image of a `Channel`, instead of updating `extraData` directly.
=> feat(llc): add name, image get, set and update on channel 

packages/stream_chat_localizations/CHANGELOG.md, packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart
fixes: #611 
* Some of the `Hindi` translations have been updated/changed for better understanding.
- 'रिप्लाई' -> 'जवाब दें'
- 'तस्वीरें' -> 'फ़ोटोज'
- 'बिता हुआ कल' -> 'कल'
- 'चैनल मौन है' -> 'चैनल म्यूट है'
=> fix(localization): Fix `Hindi` translations.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/channel_preview.dart, packages/stream_chat_flutter/lib/src/connection_status_builder.dart, packages/stream_chat_flutter/lib/src/unread_indicator.dart, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/better_stream_builder.dart, packages/stream_chat_flutter_core/lib/src/channel_list_core.dart, packages/stream_chat_flutter_core/lib/src/message_list_core.dart, packages/stream_chat_flutter_core/lib/src/message_search_list_core.dart, packages/stream_chat_flutter_core/lib/src/user_list_core.dart
1. BREAKING: Renamed `BetterStreamBuilder.loadingBuilder` to `.noDataBuilder`.
2. BREAKING: Added non-null constraint on `BetterStreamBuilder<T extends Object>`.
2. `BetterStreamBuilder.initialData` is now nullable/not-required.
=> refactor(core, ui)!: Refactor BetterStreamBuilder.

packages/stream_chat_flutter/lib/src/emoji/emoji.dart, packages/stream_chat_flutter/test/src/emoji_test.dart
This fixes the Emoji.byShortName function to do the research with shortName instead of just name. Also, this adds hashCode and equals override to the Emoji class.
=> feat(repo): Fix the wrong call on Emoji.byShortName and add hashCode and equals override to Emoji class.

packages/stream_chat/lib/src/core/http/token.dart
We were using our database user id in client JWT token. In `2.0.0-nullsafety.4` it was working properly but since we upgraded to  `2.2.1` client is failing with following error.
References #710
=> fix(llc): support for `int` user Ids in JWT tokens

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/extension.dart
Please quickly accept it and fix
During chat just type `www.google.com` and it will break the app
I use `stream_chat_flutter` and I faced one problem while 
`RangeError (index): Invalid value: Valid value range is empty: 0`  
When I dig into the code then found that capitalize is written without considering the edge case.
Edge case: If the string is empty i.e `String host = "";` we will get this error here
`RangeError (index): Invalid value: Valid value range is empty: 0`  
I fixed it and made a pull request no more big change is there.
=> fix(ui): fix capitalize extension not working on empty strings

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat_flutter/CHANGELOG.md
=> fix(llc): fixed unread count after member removed

packages/stream_chat_localizations/CHANGELOG.md, packages/stream_chat_localizations/lib/src/stream_chat_localizations_ja.dart
I am Japanese and I use Stream Chat for my Flutter app that I am releasing in Japan.
I'm very happy to see that localization has been added.
I installed it and fixed some Japanese that I found a little strange.
I did not use all the features, so it may not be perfect.
=> fix(localization): fix japanese translations

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/db/chat_persistence_client.dart
=> fix(llc): include `message.user` while saving users in persistence.

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/core/models/channel_state.dart
Fixes: https://getstream.zendesk.com/agent/tickets/19022
=> fix(llc): fix ChannelState copyWith with respect to pinnedMessages default value.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_list_view.dart, packages/stream_chat_flutter/pubspec.yaml
- Based on the conversation [here](https://github.com/GetStream/stream-chat-flutter/issues/842#issuecomment-1032767750), my project cannot upgrade to a more recent version of `stream_chat_flutter` due to a cyclic dependencies issue that I haven't fixed yet. We need this change to fix an issue on `stream_chat_flutter: ^2.0.0-nullsafety.2`. 
- I used the change from @imtoori as done [here](https://github.com/GetStream/stream-chat-flutter/commit/eb20b31c825ae430f1cdf367f40fe40e635a5cfc?diff=split) originally.
=> fix: Introduce `showFloatingDateDivider` in `MessageListView` on an older version too

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/test/src/client/channel_test.dart, packages/stream_chat/test/src/matchers.dart
When a new reaction is added to a message in a thread the `message.ownReactions` list is cleared.
https://user-images.githubusercontent.com/53336850/153057820-a64c7e41-b51d-4345-9169-9426ae387e9f.mov
Each time a user adds a reaction to a message in a thread `addMessage` is called and the modified message is added to `_threadsController` using `updateThreadInfo`.
```
/// Add a [message] to this [channelState].
void addMessage(Message message) {
if (message.parentId == null || message.showInChannel == true) {
final newMessages = List<Message>.from(_channelState.messages);
final oldIndex = newMessages.indexWhere((m) => m.id == message.id);
if (oldIndex != -1) {
Message? m;
if (message.quotedMessageId != null && message.quotedMessage == null) {
final oldMessage = newMessages[oldIndex];
m = …
```
=> fix(llc): thread message reactions not updated

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/test/src/client/channel_test.dart, packages/stream_chat/test/src/client/client_test.dart
There was already a provision to add reaction scores, via extraData in the sendReaction function at the client and channel level. While that is still possible and takes priority, I have added a named parameter named `score` so that developers can directly provide an integer score value to the sendReaction function and the SDK will handle its embedding into extraData.
=> feat(llc): Exposed score as a param for sendReaction function in client & channel

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/pubspec.yaml
fixes issue #805
I only increased the chewie version, no additional tests are needed. Existing tests pass
- Updated chewie version to 1.3.0
- Done to prevent dependency problems with BloC version (Provider versions of chewie and BloC were not compatible)
closes #805
=> fix(ui): update chewie to newest version

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/channel_list_view.dart
If a custom `onImageTap` function is not passed to `ChannelListView` then the default behaviour on tapping the `ChannelAvatar` in the `ChannelPreview` should be to take the user to the default `Channel` route.
This has been achieved by passing null to `ChannelAvatar` onTap when no custom function is passed, so that the tap action is ignored by the avatar and captured by the `ChannelPreview` widget instead.
=> fix(ui): Clicking on Avatar in ChannelPreview should go to Channel route by default

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input.dart
This fixes an issue when the available height for the mentions overlay is less than 400 (then mentions overlay overflows the top edge).
=> fix(ui): overflow of mentions overlay & input focus node

.github/workflows/stream_flutter_workflow.yml
It can be immensely aggravating to get constant emails of actions failing when adding commits to draft pull requests - #913 is a perfect example of this. I get bombarded with failure emails every time I push commits, and it's quite irritating. 
Per a GitHub Community post that I found, I have set the actions to only run on regular PR's, and a one-line action to run on drafts that just prints a message (I think this is needed for the sake of being thorough?).
=> chore(repo): Proposal: Don't run actions on draft PR's

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/attachment/url_attachment.dart, packages/stream_chat_flutter/lib/src/message_widget.dart
Closes #1003 
If the user specifies onLinkTap for MessageWidget, it now gets passed down to the UrlAttachment widget.
=> feat(ui): Add ability to specify onLinkTap for url attachments

packages/stream_chat_flutter/lib/src/message_input/stream_attachment_picker.dart
The Photo Manager plugin has now removed the `requestPermission` API that had previously been deprecated. This migrates the same code in StreamAttachmentPicker to the new API
=> Changed permission request api in attachment picker(v4)

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/core/models/channel_model.dart
=> fix(llc): merge channel in channel.update event

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input.dart
A customer reported that setting the `inputBackgroundColor` in the MessageInputTheme does not work when setting the colour as transparent. There were two widgets where the colour was not being used, I have made the change.
=> fix(ui): Use MessageInputTheme's inputBackgroundColor in MessageInput widgets

docusaurus/docs/Flutter/guides/adding_chat_to_video_livestreams.mdx
The docs for overlapping chat on a transparency background were broken because since the docs were published the MessageListViewTheme was introduced, in which the developers could set the background colour. Thew docs now account for the same.
=> doc(repo): Fixed code in the overlapping chat with transparency docs

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_list_view.dart
=> fix(ui): show date divider for first message

packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/src/core/models/attachment.dart, packages/stream_chat/lib/src/core/models/attachment.g.dart, packages/stream_chat/lib/src/core/models/channel_state.dart, packages/stream_chat/lib/src/core/models/channel_state.g.dart, packages/stream_chat/lib/src/core/models/message.g.dart, packages/stream_chat/lib/src/db/chat_persistence_client.dart, packages/stream_chat/test/src/core/api/channel_api_test.dart, packages/stream_chat/test/src/core/models/attachment_test.dart, packages/stream_chat/test/src/core/models/channel_state_test.dart, packages/stream_chat/test/src/db/chat_persistence_client_test.dart, packages/stream_chat_flutter/lib/src/attachment/giphy_attachment.dart, packages/stream_chat_flutter/lib/src/v4/message_search_list_view/stream_message_search_list_view.dart, packages/stream_chat_flutter_core/lib/src/stream_channel.dart, packages/stream_chat_persistence/example/lib/main.dart, packages/stream_chat_persistence/lib/src/dao/member_dao.dart, packages/stream_chat_persistence/lib/src/dao/message_dao.dart, packages/stream_chat_persistence/lib/src/dao/pinned_message_dao.dart, packages/stream_chat_persistence/lib/src/dao/read_dao.dart, packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart, packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart, packages/stream_chat_persistence/test/src/mapper/channel_mapper_test.dart, packages/stream_chat_persistence/test/stream_chat_persistence_client_test.dart
Having empty lists as default for model data members in LLC used to mess up the copyWith functions.
=> change(llc,core,ui,persistence): Migrate List properties in llc models to be nullable

docusaurus/docs/Flutter/guides/adding_push_notifications_v2.mdx, packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/src/core/api/device_api.dart, packages/stream_chat/test/src/client/client_test.dart, packages/stream_chat/test/src/core/api/device_api_test.dart
Push v2 supports adding a `push_provider_name` field to support creating different configurations for device and push provider.
=> feat(llc): Added a new field called push provider name in addDevice api call

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget.dart
=> fix(ui): fix message widget thread indicator in reverse mode

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/core/models/member.dart, packages/stream_chat/lib/src/core/models/member.g.dart, packages/stream_chat/test/fixtures/member.json, packages/stream_chat/test/src/core/models/member_test.dart, packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/channel_bottom_sheet.dart, packages/stream_chat_flutter/lib/src/v4/stream_channel_info_bottom_sheet.dart, packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart, packages/stream_chat_persistence/lib/src/db/drift_chat_database.g.dart, packages/stream_chat_persistence/lib/src/entity/members.dart, packages/stream_chat_persistence/lib/src/mapper/member_mapper.dart, packages/stream_chat_persistence/test/src/dao/member_dao_test.dart, packages/stream_chat_persistence/test/src/mapper/member_mapper_test.dart
Deprecated `role` field in `Member` model and did all relevant changes across packages.
=> feat(llc,ui,persistence): Deprecated Member.role in favor of Member.channelRole

packages/stream_chat/lib/src/core/http/interceptor/auth_interceptor.dart, packages/stream_chat/lib/src/core/http/stream_http_client.dart, packages/stream_chat/test/src/client/client_test.dart, packages/stream_chat/test/src/core/http/interceptor/auth_interceptor_test.dart
=> refactor(llc): remove dio deprecated methods

packages/stream_chat_localizations/lib/src/stream_chat_localizations_de.dart
-  --> Not tested, as only minor translation changes
For flagged messages the german word "markieren" only means "marked", while "melden" means "report", which is more suitable in this context.
For viewLibrary, it is better to say "öffnen" which means "open" -> as this is what happens when the user clicks this button in the app.
=> chore(localization): improve german translations

packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart, packages/stream_chat_persistence/lib/src/db/drift_chat_database.g.dart, packages/stream_chat_persistence/lib/src/entity/channels.dart, packages/stream_chat_persistence/lib/src/mapper/channel_mapper.dart, packages/stream_chat_persistence/test/src/mapper/channel_mapper_test.dart
=> feat(persistence): save channel.ownCapabilities in db

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart
=> fix(llc): Persistence not removing hidden channels.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/v4/message_input/stream_message_input.dart
The logic of finding URL matches and getting the URL to enrich the message and prepare an attachment did not allow the URLs that either had a path, eg. 'mywebsite.com/page' or query params 'google.com/search?term=flutter'.
Fixed that logic.
=> fix(ui): The URL enrichment logic does not allow path or query params in URL

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/ws/websocket.dart, packages/stream_chat/test/src/ws/websocket_test.dart
1. Send a connectUser request.
2. During the request disconnect the user and send a connectUser.
This fails currently and the websocket completely stops working 
It might fix #1086
=> fix(llc): fix connecting while connecting and disconneting

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/src/core/api/attachment_file_uploader.dart, packages/stream_chat/lib/src/core/api/stream_chat_api.dart, packages/stream_chat/lib/stream_chat.dart, packages/stream_chat/test/src/fakes.dart
This PR was created to handle these kinds of use-cases.
https://github.com/GetStream/stream-chat-flutter/pull/1225
Solution
```dart
class MyCustomUploader extends StreamAttachmentFileUploader {
const MyCustomUploader(super.client);
@override
Future<SendImageResponse> sendImage(
AttachmentFile file,
String channelId,
String channelType, {
ProgressCallback? onSendProgress,
CancelToken? cancelToken,
Map<String, Object?>? extraData,
}) async {
// ImageCompressor could be any library which supports image compression.
final compressedImage = await ImageCompressor.compress(file);
return super.sendImage(
compressedImage,
channelId,
channelType,
onSendProgress: onSendProgress,
cancelToken: cancelToken,
extraData: extraData,
);
}
}
```
```dart
/// Create a new instance of [StreamChatClient] passing …
```
=> feat(llc): add support for AttachmentFileUploaderProvider.

packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/lib/src/db/shared/native_db.dart, packages/stream_chat_persistence/lib/src/db/shared/unsupported_db.dart, packages/stream_chat_persistence/lib/src/db/shared/web_db.dart, packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart
Fix for https://github.com/GetStream/stream-chat-flutter/issues/1017
Resolves conflicts of #1016
=> feat(persistence): allow experimental indexedDB on web

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/scroll_view/message_search_scroll_view/stream_message_search_list_tile.dart
This PR fixes:
And allows the TextStyle to also have a text overflow.
Before merging, we need to choose a default behavior. 
Plain:
TextOverlow:
=> fix(ui): render overflow in message search title

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/attachment/image_attachment.dart, packages/stream_chat_flutter_core/CHANGELOG.md
Fixes https://github.com/GetStream/stream-chat-flutter/issues/1379
=> fix(ui): cached attachment image not showing on web

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/test/src/client/client_test.dart
Fixed initializing `lastSyncedDate`. It fixes the problem with missing messages inside the thread when bringing app to the foreground.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/17440581/208107800-3ee74502-f332-41e0-8ad7-55cfa8eda09a.mp4
" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/17440581/208107788-887a5a27-41c6-4028-9626-3475bd170414.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>
=> fix(llc): initializing last synced data

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_text.dart
By some reason the `MarkdownBody` widget is rendering "4+ whitespace" at the beginning of the message as a "code block" style. To fix it we are trimming the message before rendering it.
| Before | After |
| --- | --- |
| ![Screenshot from 2023-01-04 09-27-27](https://user-images.githubusercontent.com/4047514/210513971-70ec2b20-3021-430f-bcf4-da0b58d1b1e6.png)  | ![Screenshot from 2023-01-04 09-27-05](https://user-images.githubusercontent.com/4047514/210514029-b43a959c-6ffe-4d05-a996-2b53aed33d56.png) |
Fix #1424
=> fix: Trim whitespaces of a message before rendering it

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/README.md, packages/stream_chat_flutter/example/android/app/src/main/AndroidManifest.xml, packages/stream_chat_flutter/pubspec.yaml
#1431 
Updated `photo_manager` dependency in order to support Android 13.
=> chore(ui): update photo_manager dependency

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/attachment/handler/stream_attachment_handler_io.dart
Fixed temp file path on Windows. For some reason, the `tempFilePath ` contains an extra `/` at the start. Make sure it gets removed before the file is created.
=> fix(ui): temp file path on Windows

packages/stream_chat_flutter/lib/src/localization/translations.dart, packages/stream_chat_flutter/lib/src/message_list_view/unread_messages_separator.dart, packages/stream_chat_localizations/CHANGELOG.md, packages/stream_chat_localizations/example/lib/add_new_lang.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_ca.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_de.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_en.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_fr.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_it.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_ja.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_ko.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_no.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_pt.dart, packages/stream_chat_localizations/test/translations_test.dart
Changes the separator of the messages. Now it doesn't count new messages anymore. 
It is not necessary to count the new messages as this information is already available in a better place, which is the scroll button that appears when the user scrolls up. The divisor can be misleading because new messages may arrive, it should be just a marker showing when the new conversation started when the user entered a channel. 
Updating the counting inside the divisor could create performance problems because we would need to search for the divisor on every new message that arrives.
=> feat(localization): Changing new messages separator text - ISSUE-1435

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/example/lib/tutorial_part_6.dart, packages/stream_chat_flutter/lib/src/attachment/url_attachment.dart, packages/stream_chat_flutter/lib/src/theme/message_theme.dart
- ~[ ] Code changes are tested (add some information if not applicable)~ -> This is just a small customization. 
Adding the possibility to customize the number of lines in the urkl attachments.
=> feat(ui): Adding custom line for url attachment

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/attachment/giphy_attachment.dart, packages/stream_chat_flutter/lib/src/attachment/image_attachment.dart, packages/stream_chat_flutter/lib/src/attachment/image_group.dart, packages/stream_chat_flutter/lib/src/attachment/video_attachment.dart, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
Exposed `attachmentActionsModalBuilder` in `StreamMessageWidget` so it's possible to customize `ActionsModal`.
For example - you can hide `saveImage` option by using below snippet:
```
StreamMessageListView(
messageBuilder:
(context, details, messages, defaultWidget) {
return defaultWidget.copyWith(
onReplyTap: reply,
attachmentActionsModalBuilder: (_, __, defaultWidget) {
return defaultWidget.copyWith(
showSave: true,
);
}
);
},
),
```
=> feat(ui): expose attachment actions modal builder

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
=> fix(ui): `editMessageInputBuilder` property not used in message edit widget.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart
=> feat(ui): add support for `StreamMessageListView.shrinkWrap`.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
Fixes #1529: ClipboardDate text param requires non nullable string.
=> fix(ui): fix clipboardData requires non-nullable string as text.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart, packages/stream_chat_flutter/lib/src/message_widget/message_widget_content.dart
=> fix(ui): fix `StreamMessageWidget` actions dialog backdrop filter is cut off by safe area.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/theme/message_input_theme.dart
=> fix(ui): fix `MessageInputTheme.linkHighlightColor` returning null for default theme.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/message_text_field_controller.dart
=> fix(ui, core): make message input regex caseInsensitive.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
=> fix(ui): handle `StreamMessageInput` enrichUrl exceptions.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_actions_modal/message_actions_modal.dart
=> fix(ui): fix `editMessageInputBuilder` property not used in `MessageActionsModal.editMessage` option.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/scroll_view/photo_gallery/stream_photo_gallery_tile.dart
=> fix(ui): type `ImageDecoderCallback` not found on pre-Flutter 3.10.0 versions.

packages/stream_chat_flutter/lib/src/scroll_view/user_scroll_view/stream_user_list_tile.dart
fix StreamUserListTile to receive tileColor properly
the tileColor was not repassed to ListTile
=> chore(ui): StreamUserListTile to receive `tileColor` properly

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
=> fix(ui): pass onConfirmDeleteTap to MessageActionsModal.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/sending_indicator_builder.dart
=> fix(ui): fix `createdAtStyle` null check error in `SendingIndicatorBuilder`

packages/stream_chat_flutter/lib/src/message_widget/message_card.dart
Fixes the issue: https://github.com/GetStream/stream-chat-flutter/issues/1680
This PR sends the OnLinkTap to URL attachement. This is needed to customize the onLinkTap function, otherwise they does not work
=> chore(ui): Send onLinkTap on url attachement

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart
Fixes: https://getstream.zendesk.com/agent/tickets/39795
=> fix(llc): `channel.query` not initializing state.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/utils/extensions.dart, packages/stream_chat_flutter/test/src/utils/extension_test.dart
=> fix(ui): fix replaceMentions not working with usernames.

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/fullscreen_media/full_screen_media.dart, packages/stream_chat_flutter/lib/src/fullscreen_media/full_screen_media_desktop.dart
=> fix(ui): fix video player controls getting hidden.

.github/workflows/pr_title.yml, packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/pubspec.yaml, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/stream_channel_list_event_handler.dart, packages/stream_chat_flutter_core/pubspec.yaml, packages/stream_chat_localizations/CHANGELOG.md, packages/stream_chat_localizations/pubspec.yaml
* chore(repo): bump amannn/action-semantic-pull-request from 5.2.0 to 5.3.0 by @dependabot in https://github.com/GetStream/stream-chat-flutter/pull/1739
* fix(ui): fix `video_player:macos` multiple possible implementations. by @xsahil03x in https://github.com/GetStream/stream-chat-flutter/pull/1741
* feat(core): add mixin support to `StreamChannelListEventHandler`. https://github.com/GetStream/stream-chat-flutter/commit/df740186f58375007eade54a94281a1ee1b6d75d
=> Release: v6.11.0

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart, packages/stream_chat_flutter/test/src/message_actions_modal/message_actions_modal_test.dart, packages/stream_chat_flutter/test/src/mocks.dart
`showReactionPickerTail` property is bind with `showReactionPicker` as it is the only one needed to couple the reaction modal with the tail.
Closes #1759
=> fix(ui): deprecate exposed `showReactionPickerTail` in `MessageWidget`

.github/workflows/stream_flutter_workflow.yml, packages/stream_chat/test/src/core/http/stream_http_client_test.dart
Locks the flutter version in the GH actions
=> chore(repo): lock the flutter version of pipelines

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat_flutter/example/lib/debug/actions/add_user.dart, packages/stream_chat_flutter/example/lib/debug/actions/remove_user.dart, packages/stream_chat_flutter/example/lib/debug/channel_page.dart
=> fix(llc): when removing current user from channel check for null in the callback

.github/workflows/docusaurus.yml, .github/workflows/pr_title.yml, .github/workflows/stream_flutter_workflow.yml, packages/stream_chat_flutter/pubspec.yaml
=> chore(repo): sync branches

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/test/src/client/channel_test.dart
=> fix(llc): delete image and file attachments from the CDN, when the message get's deleted

packages/stream_chat_flutter/test/src/message_input/command_button_test.dart
=> test(ui): add more coverage in CommandButton

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/bottom_row.dart, packages/stream_chat_flutter/test/src/message_list_view/bottom_row_test.dart, packages/stream_chat_flutter/test/src/mocks.dart
Be lenient on the presence of `onThreadTap` paramenter in `BottomRow` component.
Error:
```
I/flutter (30434): Error while fetching message: Null check operator used on a null value, #0      BottomRow.build._onThreadTap (package:stream_chat_flutter/src/message_widget/bottom_row.dart:172:27)
```
=> fix(ui): be lenient when calling nullable onThreadTap method

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart
We encountered a bug in our messaging feature where quoted messages were inadvertently marked as deleted when replying within a thread. This behavior was linked to the `updateMessage` method's logic, which inaccurately managed the state of quoted messages during updates, particularly in thread reply scenarios.
The core of the issue was found in the original implementation of the `updateMessage` method within the `Channel` class. The method indiscriminately updated quoted messages whenever an updating message's ID matched that of a quoted message, leading to quoted messages being marked as deleted by mistake, simply due to their reference in updates or replies.
The fix involved a strategic refactor of the `updateMessage` method to ensure updates to messages, especially regarding quoted …
=> fix(llc): reply being considered deleted if a new message was typed inside its thread

tools/version.sh
=> chore(repo): add command line tool to update versions in all packages

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/gallery/gallery_footer.dart, packages/stream_chat_flutter/lib/src/gallery/gallery_header.dart, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart, packages/stream_chat_flutter/lib/src/message_widget/bottom_row.dart, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart, packages/stream_chat_flutter/lib/src/scroll_view/photo_gallery/stream_photo_gallery_tile.dart, packages/stream_chat_flutter/lib/src/stream_chat.dart, packages/stream_chat_flutter/lib/src/utils/extensions.dart, packages/stream_chat_flutter/lib/src/utils/typedefs.dart, packages/stream_chat_flutter/test/scrollable_positioned_list/scrollable_positioned_list_test.dart
=> fix(ui): migrate components to material 3 and remove interception

docusaurus/docs/Flutter/02-stream_chat_flutter/03-custom_widgets/01-customize_message_widget.mdx, packages/stream_chat_flutter/lib/src/dialogs/confirmation_dialog.dart, packages/stream_chat_flutter/lib/src/gallery/gallery_header.dart, packages/stream_chat_flutter/lib/src/message_widget/bottom_row.dart, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart, packages/stream_chat_flutter/lib/src/scroll_view/photo_gallery/stream_photo_gallery_tile.dart, packages/stream_chat_flutter/lib/src/stream_chat.dart, packages/stream_chat_flutter/lib/src/theme/stream_chat_theme.dart, packages/stream_chat_flutter/lib/src/utils/extensions.dart, packages/stream_chat_flutter/lib/src/utils/typedefs.dart
=> docs(ui): document reaction icon customization

docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_8_0.mdx, packages/stream_chat_flutter/lib/src/stream_chat.dart, packages/stream_chat_flutter/test/src/avatars/group_avatar_test.dart, packages/stream_chat_flutter/test/src/bottom_sheets/edit_message_sheet_test.dart, packages/stream_chat_flutter/test/src/bottom_sheets/error_alert_sheet_test.dart, packages/stream_chat_flutter/test/src/gallery/gallery_footer_test.dart, packages/stream_chat_flutter/test/src/gallery/gallery_header_test.dart, packages/stream_chat_flutter/test/src/material_app_wrapper.dart, packages/stream_chat_flutter/test/src/message_widget/deleted_message_test.dart, packages/stream_chat_flutter/test/src/message_widget/message_text_test.dart, packages/stream_chat_flutter/test/src/misc/reaction_bubble_test.dart, packages/stream_chat_flutter/test/src/misc/system_message_test.dart, packages/stream_chat_flutter/test/src/mocks.dart, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/stream_chat_core.dart, packages/stream_chat_flutter_core/pubspec.yaml, packages/stream_chat_flutter_core/test/stream_chat_core_test.dart
=> feat(core): migrate connectivity_plus library

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart, packages/stream_chat_flutter/lib/src/utils/extensions.dart, packages/stream_chat_flutter/test/src/utils/extension_test.dart
Take into account the lastReadMessageId property
=> fix(ui): microseconds diffs result in wrong unread indicator

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/attachment/builder/attachment_widget_builder.dart, packages/stream_chat_flutter/lib/src/message_widget/parse_attachments.dart
PR based on #1826 
The attachment builder now expects custom attachments only and adds the attachment builders for the normal attachment types by default.
Old:
```dart
messageWidget.copyWith(
// ....
attachmentBuilders: [
CustomBuilder()
...StreamAttachmentWidgetBuilder.defaultBuilders(message: messageDetails.message),
],
);
```
New:
```dart
messageWidget.copyWith(
// ....
attachmentBuilders: [
CustomBuilder()
],
);
```
OR 
```dart
messageWidget.copyWith(
// ....
attachmentBuilders: [
...StreamAttachmentWidgetBuilder.defaultBuilders(
message: messageDetails.message,
customAttachmentBuilders: [
CustomBuilder(),
],
),
],
);
```
=> fix(ui): custom attachment builders

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
Fixes #1929 
Currently copying a message does not replace the mentioned IDs with user names. This PR uses the same logic from the package that fixes this in the message text to fix it.
=> fix(ui): fixes copying a message with mentions

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/channel/stream_channel_avatar.dart
Fixes #1931
`ChannelHeader` no longer uses `CachedNetworkImage` if channel image is not set.
=> fix(ui): stops cached image from being used when channel image is not set

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/channel/stream_channel_avatar.dart, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
Fixes #1879 
Reaction picker tails are currently visible in the list view and also show when reaction picker is disabled. This PR exposes a new property for enabling and disabling the tail as well as a default calculation for when the tail should be enabled.
=> fix(ui): added calculation for reaction picker tail

packages/stream_chat/lib/src/client/client.dart, packages/stream_chat_flutter/lib/src/fullscreen_media/full_screen_media_desktop.dart, packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager_desktop.dart, packages/stream_chat_flutter/pubspec.yaml
Switched to `media_kit` because `dart_vlc` is deprecated.
=> fix(repo): switch to media_kit

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/stream_chat_core.dart
=> fix(core): fixed background events being called in foreground

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/src/core/api/stream_chat_api.dart, packages/stream_chat/lib/src/core/http/stream_http_client.dart, packages/stream_chat/test/src/core/http/adapter/custom_adapter_test.dart
=> feat(llc): allow setting http client adapter to use native http

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/attachment_picker/stream_attachment_picker_bottom_sheet.dart, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
Adds the `useNativePickerOnMobile` boolean to force use of native picker on mobile platforms.
=> fix(ui): added option to use native picker for mobile

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
Fixed bug with some URLs enriching twice in a message.
=> fix(ui): updated regex for enriching urls

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/video/video_service.dart, packages/stream_chat_flutter/lib/src/video/video_thumbnail_image.dart, packages/stream_chat_flutter/pubspec.yaml
=> fix(ui): namespace not specified for video_thumbnail package.

.gitattributes
This pull request includes a small change to the `.gitattributes` file to improve the handling of generated files in diffs. The change ensures that generated files are skipped from showing up in diffs.
* [`.gitattributes`](diffhunk://#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR1-R3): Added rules to mark `*.g.dart` and `*.freezed.dart` files as generated, preventing them from appearing in diffs.
=> chore(repo): add .gitattributes to skip generated files in diffs

.github/workflows/stream_flutter_workflow.yml
This pull request includes a change to the `.github/workflows/stream_flutter_workflow.yml` file. The change reduces the minimum coverage threshold for the Stream Chat package from 79% to 70%.
* [`.github/workflows/stream_flutter_workflow.yml`](diffhunk://#diff-9960b9c55cd9e93e8569eeff325f7266be775b264b2fb1a4fda10ead963bf694L115-R115): Reduced the `min_coverage` value from 79 to 70 for the Stream Chat package.
=> ci(repo): update min coverage for llc

.github/workflows/stream_flutter_workflow.yml, packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/poll/stream_poll_comments_dialog.dart, packages/stream_chat_flutter/lib/src/poll/stream_poll_option_votes_dialog.dart, packages/stream_chat_flutter/lib/src/poll/stream_poll_options_dialog.dart, packages/stream_chat_flutter/lib/src/poll/stream_poll_results_dialog.dart
This pull request addresses a bug fix in the `stream_chat_flutter` package, ensuring that the `StreamChannel` is properly available in the widget tree for various poll-related dialogs. The changes primarily involve wrapping the `ValueListenableBuilder` in a `StreamChannel` widget to provide the necessary context.
Bug Fixes:
* [`packages/stream_chat_flutter/CHANGELOG.md`](diffhunk://#diff-739738ae3e48428d9cb405ab14bc8a9b64c9faa943305d6a15c9d6f7810b6b04R1-R6): Added a note about the fix for `StreamChannel` not being available in the widget tree for various poll options.
Poll Dialogs:
* [`packages/stream_chat_flutter/lib/src/poll/stream_poll_comments_dialog.dart`](diffhunk://#diff-db24a6040b0156cdcaa6d62816f3b22cc0336ed4e2984184b60551f25f2fc7ecL24-R26): Wrapped `ValueListenableBuilder` in a …
=> fix(ui): fix StreamChannel not available in various poll dialogs

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/src/core/api/moderation_api.dart, packages/stream_chat/lib/src/ws/websocket.dart, packages/stream_chat/lib/stream_chat.dart, packages/stream_chat/test/src/core/http/interceptor/auth_interceptor_test.dart, packages/stream_chat/test/src/ws/websocket_test.dart
- https://linear.app/stream/issue/CHA-546/push-notification-template-bug
- https://github.com/GetStream/chat/pull/7924
- https://github.com/GetStream/chat/pull/7913
=> feat(llc): allow overridding websocket baseUrl

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart, packages/stream_chat_flutter/lib/src/message_widget/message_widget_content.dart
Fixes a part of https://getstream.zendesk.com/agent/tickets/60177
This pull request includes changes to fix a bug in the `StreamMessageWidget` and improve the handling of pinned messages. The most important changes are related to ensuring that deleted messages do not show as pinned and updating the conditions for displaying pinned message highlights.
Bug fixes and improvements:
* [`packages/stream_chat_flutter/CHANGELOG.md`](diffhunk://#diff-739738ae3e48428d9cb405ab14bc8a9b64c9faa943305d6a15c9d6f7810b6b04R6): Added a note about fixing the `MessageWidget` showing pinned background for deleted messages.
* [`packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart`](diffhunk://#diff-fa3baf3c1e6d70317fe6b3b7eb39de4182546c0664d17ff6095cd4368107b380L608-R608): Updated the …
=> fix(ui): fix deleted messages showing pinned background.

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/core/models/channel_config.dart, packages/stream_chat/lib/src/core/models/channel_config.g.dart, packages/stream_chat/lib/src/core/models/event.dart, packages/stream_chat/lib/src/core/models/event.g.dart, packages/stream_chat/lib/src/core/models/message.dart, packages/stream_chat/lib/src/core/models/message.g.dart, packages/stream_chat/test/fixtures/channel_state.json, packages/stream_chat/test/fixtures/event.json, packages/stream_chat/test/fixtures/message.json, packages/stream_chat/test/fixtures/message_to_json.json, packages/stream_chat/test/src/client/channel_test.dart, packages/stream_chat/test/src/core/models/channel_state_test.dart, packages/stream_chat/test/src/core/models/event_test.dart, packages/stream_chat/test/src/core/models/message_test.dart
This pull request includes several changes to the `stream_chat` package, focusing on improving the handling of system messages, updating the logic for message visibility, and enhancing the persistence of channel states. Below are the most important changes:
* Added support for system messages not updating `channel.lastMessageAt` in `CHANGELOG.md`.
* Introduced a new method `_shouldUpdateChannelLastMessageAt` in `ChannelClientState` to determine if the last message time should be updated based on message properties.
* Refactored the debounced update logic for channel state persistence in `ChannelClientState` to use a more concise `debounce` function.
* Modified the logic to calculate the new last message time in `ChannelClientState`, ensuring it only updates when necessary.
* Added …
=> feat(llc): add support for system messages not updating `channel.lastMessageAt`

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/core/models/message.dart, packages/stream_chat/lib/src/core/models/message.g.dart, packages/stream_chat/test/fixtures/channel_state_to_json.json, packages/stream_chat/test/fixtures/message_to_json.json, packages/stream_chat/test/src/core/models/channel_test.dart, packages/stream_chat/test/src/core/models/message_test.dart, packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart, packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart, packages/stream_chat_persistence/lib/src/db/drift_chat_database.g.dart, packages/stream_chat_persistence/lib/src/entity/messages.dart, packages/stream_chat_persistence/lib/src/mapper/message_mapper.dart, packages/stream_chat_persistence/lib/src/mapper/pinned_message_mapper.dart, packages/stream_chat_persistence/test/src/mapper/message_mapper_test.dart, packages/stream_chat_persistence/test/src/mapper/pinned_message_mapper_test.dart
Fixes: [FLU-29](https://linear.app/stream/issue/FLU-29)
This pull request introduces support for sending private or restricted visibility messages in the `stream_chat` package. The changes include updates to the message visibility logic, serialization, and the user interface to handle these new message types.
Key changes:
* [`packages/stream_chat/CHANGELOG.md`](diffhunk://#diff-0a4071421926a484a5e4e46567cd96230a5754549ea0a7198146eced8598442dR15): Added support for sending private or restricted visibility messages.
* [`packages/stream_chat/lib/src/core/models/message.dart`](diffhunk://#diff-d3e3b9e6b3253e66b920f443ff73bdc4c0a0c082d38c6cefb05cc866792cf3b4L241-R246): Updated the `Message` class to include a `restrictedVisibility` field and added an extension for visibility control methods. …
=> feat(llc, ui, persistence): add support for private messages

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/attachment_picker/stream_attachment_picker_bottom_sheet.dart, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart, packages/stream_chat_flutter/lib/src/theme/message_input_theme.dart, packages/stream_chat_flutter/lib/src/theme/stream_chat_theme.dart
This pull request introduces a new feature for the `StreamMessageInput` component to support using the system's default media picker. Additionally, it includes various updates to the theme data to support this new feature.
* Introduced `StreamMessageInput.useSystemAttachmentPicker` to allow using the system's default media picker for attachment selection. This provides a consistent user experience, reduces the need for additional permissions, and simplifies implementation. [[1]](diffhunk://#diff-739738ae3e48428d9cb405ab14bc8a9b64c9faa943305d6a15c9d6f7810b6b04R8-R15) [[2]](diffhunk://#diff-7087319571f4a5913a123c0f9cbe924de54094ccf1831840a225e2afff17d040R82-R83) [[3]](diffhunk://#diff-bae4e8bdf40b464850693cbdf2973ec45dedbc41a5e55f1cda0f4bde183b9df3L160-R168) …
=> feat(ui): introduce useSystemAttachmentPicker for system media picker support

packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/core/util/extension.dart, packages/stream_chat/lib/src/ws/websocket.dart, packages/stream_chat_flutter_core/lib/src/stream_channel.dart
Resolves: https://getstream.zendesk.com/agent/tickets/60248
* [`packages/stream_chat/lib/src/core/util/extension.dart`](diffhunk://#diff-1b8e096178b5dc00d26fb8ef59152cd6674779e867beb24865e97da1628368cdR1-R2): Added a new extension `StreamControllerX` with methods `safeAdd` and `safeAddError` to safely add events and errors to the `StreamController` without causing exceptions if the controller is closed. [[1]](diffhunk://#diff-1b8e096178b5dc00d26fb8ef59152cd6674779e867beb24865e97da1628368cdR1-R2) [[2]](diffhunk://#diff-1b8e096178b5dc00d26fb8ef59152cd6674779e867beb24865e97da1628368cdR32-R48)
* [`packages/stream_chat/lib/src/client/channel.dart`](diffhunk://#diff-f5b3c73311cd4ed2f91bb08aff0ca7385d4494f7e44294e082a0eb3aefee58cbL2198-R2198): Updated the `isUpToDate`, `_channelState`, and …
=> refactor(llc): safeAdd data to streamControllers

packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/stream_channel_list_event_handler.dart
FLU-58
Fixes #1894
When we enter `onChannelVisible` we are sure that the state is a Success state. However, when we call `controller.getChannel` we can go to loading state. So by moving the `controller.currentItems` before the `getChannel` we are always in a Success state.
=> fix(core): move get currentChannels before async

melos.yaml, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/pubspec.yaml
I think [this is the breaking change in device_info_plus](https://github.com/fluttercommunity/plus_plugins/pull/3254/files#diff-b8d645085361575caa53bac8c308002b566d8d61aab91b189a158a39518c6e92), this is not relevant for us and it's better for customers if we allow for a broader range of dependencies so we don't conflict with other packages.
=> fix(core): allow for device_info_plus v10

packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/permission_type.dart, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart, packages/stream_chat_flutter/test/src/bottom_sheets/edit_message_sheet_test.dart, packages/stream_chat_flutter/test/src/message_actions_modal/message_actions_modal_test.dart, packages/stream_chat_flutter/test/src/message_input/message_input_test.dart, packages/stream_chat_flutter_core/lib/src/stream_message_input_controller.dart
Resolves: FLU-68
The PR aims to move the slow mode logic from the `StreamMessageInput` widget to the `StreamMessageInputController` so that it can be directly accessed and handled through the controller.
Additionally, it improves the current cooldown logic in Channel and maintains the cooldown through out the app restart.
https://github.com/user-attachments/assets/a71fdf2e-631d-4f8d-86f4-ebb5bb934f3a
=> refactor(llc, ui): move slowMode logic inside StreamMessageInputController

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/countdown_button.dart, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart, packages/stream_chat_flutter/lib/src/message_input/stream_message_send_button.dart, packages/stream_chat_flutter/test/src/message_input/stream_message_send_button_test.dart
Resolves: FLU-27
* **Customization Fixes:**
* Fixed an issue where message input buttons could not be customized (`packages/stream_chat_flutter/CHANGELOG.md`).
* **Deprecations and Replacements:**
* Deprecated `idleSendButton` and `activeSendButton` in favor of `idleSendIcon` and `activeSendIcon` in `StreamMessageInput` and `StreamMessageSendButton` classes (`packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart`). [[1]](diffhunk://#diff-bae4e8bdf40b464850693cbdf2973ec45dedbc41a5e55f1cda0f4bde183b9df3L128-R130) [[2]](diffhunk://#diff-bae4e8bdf40b464850693cbdf2973ec45dedbc41a5e55f1cda0f4bde183b9df3L295-R317) [[3]](diffhunk://#diff-96909356ef574f308b983ed0a540ebb361ffc0a289f601d49ecfbee3ac33a609L18-R32) [[4]](diffhunk://#diff-96909356ef574f308b983ed0a540ebb361ffc0a289f …
=> fix(ui): fix message input send button not customisable

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/core/models/channel_model.dart, packages/stream_chat/lib/src/core/models/channel_model.g.dart, packages/stream_chat/lib/src/permission_type.dart, packages/stream_chat/test/src/client/channel_test.dart, packages/stream_chat_flutter/lib/src/bottom_sheets/stream_channel_info_bottom_sheet.dart, packages/stream_chat_flutter/lib/src/message_actions_modal/message_actions_modal.dart, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart, packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart, packages/stream_chat_flutter/lib/src/message_widget/reactions/message_reactions_modal.dart, packages/stream_chat_flutter/test/src/message_actions_modal/message_actions_modal_test.dart, packages/stream_chat_flutter/test/src/mocks.dart, sample_app/lib/widgets/channel_list.dart
This pull request introduces significant improvements to the `stream_chat` package by refactoring user capabilities into a more structured format. The changes include replacing the `PermissionType` with a new `ChannelCapability` extension type and adding convenience methods to check user capabilities.
=> refactor(llc, ui): introduce 'ChannelCapability' and deprecate 'PermissionType'

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart, packages/stream_chat_flutter/test/src/message_input/message_input_test.dart
Fixes: #2042 
This pull request includes several updates to the `StreamMessageInput` component in the `stream_chat_flutter` package, focusing on improving message validation and key event handling.
**Bug Fixes:**
* Fixed the `StreamMessageInput` send message predicate to ensure proper message sending behavior.
**Code Enhancements:**
* Improved the `_defaultValidator` method to better handle message validation by checking for non-empty text and attachments.
* Refined the `_defaultSendMessageKeyPredicate` method to handle key events more accurately by considering platform-specific behavior and shift key status.
* Updated the `_defaultClearQuotedMessageKeyPredicate` method to clear quoted messages based on the escape key press, with platform-specific handling.
* Simplified the …
=> fix(ui): fix message input send message key predicate

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/src/core/models/channel_state.dart, packages/stream_chat/lib/src/core/models/member.dart, packages/stream_chat/test/src/client/channel_test.dart, packages/stream_chat/test/src/client/retry_queue_test.dart, packages/stream_chat/test/src/fakes.dart, packages/stream_chat/test/src/mocks.dart, packages/stream_chat_flutter_core/lib/src/stream_channel_list_event_handler.dart
Resolves: #1964 
This PR fixes an issue where the channel membership is not getting updated when a member update event is received. Additionally, it also improves the test mock classes for better testing for ws events.
=> fix(llc): fix channel membership not updated

packages/stream_chat_flutter/lib/src/channel/stream_message_preview_text.dart, packages/stream_chat_flutter/lib/src/localization/translations.dart, packages/stream_chat_flutter/lib/src/scroll_view/channel_scroll_view/stream_channel_list_tile.dart, packages/stream_chat_flutter/test/src/channel/stream_message_preview_text_test.dart, packages/stream_chat_flutter/test/src/localization/default_translations_test.dart, packages/stream_chat_flutter/test/src/scroll_view/thread_scroll_view/stream_thread_list_tile_test.dart, packages/stream_chat_localizations/CHANGELOG.md, packages/stream_chat_localizations/example/lib/add_new_lang.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_ca.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_de.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_en.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_fr.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_it.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_ja.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_ko.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_no.dart, packages/stream_chat_localizations/lib/src/stream_chat_localizations_pt.dart, packages/stream_chat_localizations/test/translations_test.dart
Resolves: FLU-89
This pull request includes significant changes to the `stream_chat_flutter` package to improve message preview functionality and localization support. The most important changes include refactoring the `StreamMessagePreviewText` class, adding new translation strings, and updating the `ChannelLastMessageText` class.
* [`stream_message_preview_text.dart`](diffhunk://#diff-90b9c414677a57502bf85d06926543f0fd1b2b4f88eed488f9855ecdb801fd3cL23-R193): Refactored the `StreamMessagePreviewText` class to improve message preview logic, including handling of mentions, attachments, and polls. Added helper methods `_getPreviewText`, `_pollPreviewText`, and `_previewMessageContextText` to streamline the preview text generation.
* …
=> refactor(ui): refactor message preview text to support polls

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/client.dart, packages/stream_chat/lib/src/core/models/own_user.dart, packages/stream_chat/lib/src/core/models/own_user.g.dart, packages/stream_chat/test/src/client/client_test.dart
Resolves: FLU-86
Improves user blocking functionality by updating client state when blocking/unblocking users:
- `client.blockUser` now updates `currentUser.blockedUserIds` list with newly blocked user IDs.
- `client.unblockUser` now removes the unblocked user ID from `currentUser.blockedUserIds` list.
- `client.queryBlockedUsers` now updates `currentUser.blockedUserIds` with the latest blocked users data.
=> feat(llc): add support for OwnUser.blockedUserIds

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
Resolves: FLU-94, #2150 
Removed `.replaceMentionsWithId()` call during message sending to ensure push notifications display proper usernames when users are mentioned.
=> fix(ui): remove replacing mentions with id while sending message

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/lib/src/core/models/event.dart, packages/stream_chat/lib/src/core/models/event.g.dart, packages/stream_chat/lib/src/core/models/read.dart, packages/stream_chat/test/src/client/channel_test.dart, packages/stream_chat/test/src/core/models/event_test.dart, packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart, packages/stream_chat_flutter/lib/src/message_list_view/mlv_utils.dart, packages/stream_chat_flutter/lib/src/message_list_view/unread_indicator_button.dart, packages/stream_chat_flutter/lib/src/utils/extensions.dart, packages/stream_chat_flutter/test/src/message_list_view/message_list_view_test.dart, packages/stream_chat_flutter/test/src/utils/extension_test.dart, packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/stream_channel.dart, packages/stream_chat_flutter_core/test/stream_channel_test.dart, sample_app/lib/pages/thread_page.dart
This PR adds unread message indicators and fixes several read state tracking bugs. Key changes:
- Added `UnreadIndicatorButton` widget to display unread message counts
- Enhanced `Event` model with `unreadMessages` and `lastReadMessageId` fields
- Fixed message list scroll behavior when navigating to unread messages
- Improved read event handling in the Channel class
- #2184 - Messages not marked as read when scrolled to bottom
- #2187 - StreamMessageListView scrolls back up after reaching bottom
- #2085 - Read state not properly updated with messageRead events
=> fix(llc, core, ui): fix mark unread issues

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/test/src/client/channel_test.dart
Resolves: FLU-74
This pull request fixes `channelState.unreadCount` not updating if the user is not part of the read list.
=> fix(llc): unread count not updating for newly joined channels

packages/stream_chat/lib/src/db/chat_persistence_client.dart, packages/stream_chat/test/src/db/chat_persistence_client_test.dart, packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/lib/src/dao/dao.dart, packages/stream_chat_persistence/lib/src/dao/draft_message_dao.dart, packages/stream_chat_persistence/lib/src/dao/draft_message_dao.g.dart, packages/stream_chat_persistence/lib/src/dao/message_dao.dart, packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart, packages/stream_chat_persistence/lib/src/db/drift_chat_database.g.dart, packages/stream_chat_persistence/lib/src/entity/draft_messages.dart, packages/stream_chat_persistence/lib/src/entity/entity.dart, packages/stream_chat_persistence/lib/src/entity/messages.dart, packages/stream_chat_persistence/lib/src/mapper/draft_message_mapper.dart, packages/stream_chat_persistence/lib/src/mapper/mapper.dart, packages/stream_chat_persistence/lib/src/mapper/message_mapper.dart, packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart, packages/stream_chat_persistence/test/mock_chat_database.dart, packages/stream_chat_persistence/test/src/dao/draft_message_dao_test.dart, packages/stream_chat_persistence/test/src/mapper/draft_message_mapper_test.dart, packages/stream_chat_persistence/test/stream_chat_persistence_client_test.dart
Resolves: FLU-109
This pull request introduces support for draft messages in the `stream_chat_persistence`.
=> feat(persistence): add support for DraftMessages

packages/stream_chat_flutter_core/lib/src/stream_message_input_controller.dart, packages/stream_chat_flutter_core/test/stream_message_input_controller_test.dart
This PR adds tests for the StreamMessageInputController class, providing thorough coverage for its functionality including:
- Initialization tests with different constructors
- Text manipulation
- Quoted message handling
- Command handling
- Show in channel functionality
- Attachments management
- OG attachment specific handling
- Poll management
- Mentioned users functionality
- Cooldown timer validation
- Reset and clear operations
- Restorable controller functionality
The tests ensure that all edge cases are handled properly and that the controller behaves as expected in all scenarios.
=> chore(core): Add tests for StreamMessageInputController

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/core/models/own_user.dart, packages/stream_chat/lib/src/core/models/own_user.g.dart, packages/stream_chat/lib/src/core/models/user.dart, packages/stream_chat/lib/src/core/models/user.g.dart, packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/lib/src/db/drift_chat_database.g.dart, packages/stream_chat_persistence/lib/src/entity/users.dart, packages/stream_chat_persistence/lib/src/mapper/user_mapper.dart, packages/stream_chat_persistence/test/src/dao/user_dao_test.dart, packages/stream_chat_persistence/test/src/mapper/user_mapper_test.dart
Resolves: FLU-90
This pull request introduces support for team roles for users in the `stream_chat` and `stream_chat_persistence` package. The changes include updates to the `User` and `OwnUser` models and entities.
=> feat(llc): add teams role support for users

.github/workflows/distribute_external.yml
This PR removes the bootstrap step from the external distribution workflow as the external builds should rely on packages released on pub.dev not local overridden packages.
=> refactor(repo): external releases should only use pub dependencies

.github/PULL_REQUEST_TEMPLATE.md
This updates the pull request template. The main change is to add linear and (optional) github tickets and some comments what is expected of the PR submitter. Those comments are not visible on regular view, so don't have to be removed when you create a PR.
=> chore(repo): Update PULL_REQUEST_TEMPLATE

packages/stream_chat_persistence/CHANGELOG.md, packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart
Github Issue: #2034 
This PR fixes a case in `persistence.getChannelStates` method where the pagination.offset can be greater than the `channelStates.length` which results in an exception. The fix now clamps the offset before applying it to the channelStates.
=> fix(persistence): improve pagination handling by clamping offset

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/client/channel.dart, packages/stream_chat/test/src/client/channel_test.dart
Github Issue: #2013
If you pin message, `channel.state.pinnedMessages` starts to store message twice. There already [was a fix](https://github.com/GetStream/stream-chat-flutter/pull/894) for such an issue, but for some reason it was overwritten later. I reapplied it and also added test
=> fix(llc): fix pinned message get duplicated

packages/stream_chat_flutter_core/CHANGELOG.md, packages/stream_chat_flutter_core/lib/src/stream_channel.dart
Zendesk: [65188](https://getstream.zendesk.com/agent/tickets/65188)
This pull request addresses a bug in the `StreamChannel` component which now ensures that loading a channel at `lastReadMessageId` now gracefully handles situations where the channel exceeds the member threshold by falling back to loading at the `lastRead` date.
=> fix(core): Fallback to loading channel at last read date when loadChannelAtMessage fails

sample_app/ios/Runner/Info.plist
Added the `ITSAppUsesNonExemptEncryption` key with a value of `false`, indicating that the app does not use non-exempt encryption.
This is needed otherwise, AppStore complains about `Missing Compliance status in TestFlight`.
=> fix(samples): mark ITSAppUsesNonExemptEncryption to false

melos.yaml, packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/pubspec.yaml
This pull request bumps dependencies for the following packages.
* Updated `just_audio` to ">=0.9.38 <0.11.0"` in `melos.yaml` and `pubspec.yaml` for stream_chat_flutter.
=> chore(ui): bump just_audio from 0.9.46 to 0.10.2

packages/stream_chat_flutter/CHANGELOG.md, packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
**Fixed `StreamMessageInput` exception**: Updated the `StreamMessageInput` widget to handle cases where the `Channel` is not initialized. This change introduces a conditional logic using a `switch` statement to ensure the widget behaves correctly even when `channel.state` is `null`. (`packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart`)
=> fix(ui): fix MessageInput to use with non-initialized channel

packages/stream_chat/CHANGELOG.md, packages/stream_chat/lib/src/ws/websocket.dart
Linear: fixes FLU-142
Github Issue: fixes #2218
We have a null check operator on `connectionCompleter`. This can only be `null` if there is a disconnect while fetching a token. Now we return the connectionCompleter future before we go async, so this should never happen anymore.
We didn't reproduce it, so it's also hard to test.
=> fix(llc): null check on websocket connection
