- lib/src/message_list_view.dart
> add date separators

- lib/src/message_input.dart
Fix for #32 
Removed the Flex that was causing the widget to overflow. Also did it for the Mentions Overlay.
> Fix for #32. Removed the Flex causing the widget to overflow

- lib/src/channel_image.dart
- lib/src/channel_name.dart
> Adding support for one-on-one conversation to channel preview

- .github/workflows/main.yml
- lib/src/channel_image.dart
- lib/src/typing_indicator.dart
- pubspec.yaml
- test/src/channel_preview_test.dart
Add basic testing for channel_preview widget
This is just a start to have basic CI checks
More tests to be added
> add basic testing for channel_preview widget

- CHANGELOG.md
- lib/src/message_input.dart
- pubspec.yaml
Release 0.2.8+1 updating dependencies
> version bump

- CHANGELOG.md
- pubspec.yaml
> bump version

- lib/src/full_screen_video.dart
> add back button on full screen video page

- lib/src/message_input.dart
Removes overflow in favor of clipBehavior
> fix: Removed overflow parameter and migrated to clipBehavior

- lib/src/message_input.dart
Capitalizes the start of sentences.
> fix: Auto capitalize the start of sentences

- .gitignore
- example/pubspec.yaml
- lib/src/back_button.dart
- lib/src/channel_header.dart
- lib/src/thread_header.dart
- lib/stream_chat_flutter.dart
With the last Flutter update the back icon was not centered anymore.
I extracted the backButton and make it configurable while using another icon that is centered.
> center back button extracting the widget

- lib/src/message_actions_bottom_sheet.dart
- lib/src/reaction_picker.dart
- lib/src/user_reaction_display.dart
Adds a row of reaction user avatars above reaction buttons
> feat: Added reaction faces to bottom sheet

- CHANGELOG.md
- example/pubspec.yaml
- lib/src/channels_bloc.dart
- lib/src/message_list_view.dart
- lib/src/stream_channel.dart
- lib/src/thread_header.dart
- pubspec.yaml
> update llc dependency and hotfixes

- example/lib/single_conversation.dart
- example/pubspec.yaml
> fix single conversation example

- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/pubspec.yaml
> Refs #109: update sample app gradle

- CHANGELOG.md
- lib/src/channel_list_view.dart
- lib/src/channel_preview.dart
- lib/src/unread_indicator.dart
- pubspec.yaml
> use channe.state.unreacCountStream

- analysis_options.yaml
- lib/src/message_actions_modal.dart
- lib/src/message_input.dart
- pubspec.yaml
Added new GIPHHY input
New input UI 
New mentions UI 
New Edit UI
> New Message Input 

- lib/src/message_list_view.dart
- pubspec.yaml
Adds date header to message list
> Date header

- .github/workflows/main.yml
> trigger action on prs on every branch

- lib/src/message_input.dart
> adapt file picker to web

- lib/src/message_reactions_modal.dart
- lib/src/reaction_picker.dart
> Reactions fix

- CHANGELOG.md
- example/lib/main.dart
- example/pubspec.yaml
- lib/src/stream_chat.dart
- pubspec.yaml
> channel query on local notification was using event.type

- .github/workflows/test.yml
- example/lib/main.dart
> Add flutter format check in test.yml

- CHANGELOG.md
- lib/src/message_list_view.dart
- lib/src/message_widget.dart
- lib/src/system_message.dart
- pubspec.yaml
> add message tap callbacks

- lib/src/channel_header.dart
- lib/src/channel_info.dart
- lib/src/typing_indicator.dart
> feat : channel header status

- .gitignore
- example/lib/main.dart
- example/lib/search_text_field.dart
- example/pubspec.yaml
- lib/src/channel_bottom_sheet.dart
- lib/src/channel_name.dart
- lib/src/message_search_bloc.dart
- lib/src/message_search_item.dart
- lib/src/message_search_list_view.dart
- lib/src/stream_chat_theme.dart
- lib/src/user_list_view.dart
- lib/stream_chat_flutter.dart
- pubspec.yaml
> feat : MessageSearchListView

- example/lib/choose_user_page.dart
- example/lib/group_chat_details_screen.dart
- example/lib/main.dart
- example/lib/new_chat_screen.dart
- example/lib/routes/app_routes.dart
- example/lib/routes/routes.dart
- lib/stream_chat_flutter.dart
Signed-off-by: Sahil Kumar <xdsahil@gmail.com>
> Add bottomNavigationBar

- lib/src/channel_list_view.dart
> add onLongPress on channel when using custom channel builder

- .github/workflows/flutter-analyze.yml
> Add dart analyser action

- lib/src/message_list_view.dart
> do not call markread if channel does not support it

- lib/src/message_input.dart
> Make public autofocus field of the TextField of message_input

- .github/workflows/flutter-analyze.yml
Signed-off-by: Ayush P Gupta <ayushpguptaapg@gmail.com>
This PR aims to add a safety code format check when raising a PR or pushing any commits.
This ensures the code is properly formatted. The check would simply fail if any of the files can be formatted with `flutter format .`
No breaking change. But not tested as it must be run on Github Action, although it's tested in my other repositories.
> Add code formatting check

- lib/src/file_attachment.dart
- lib/src/media_list_view.dart
- lib/src/media_utils.dart
- lib/src/message_input.dart
- lib/src/url_attachment.dart
> Qa fix attachments

- lib/src/message_input.dart
> QA fix for file list

- CHANGELOG.md
- lib/src/channel_preview.dart
- lib/src/message_list_view.dart
- lib/src/stream_chat.dart
- pubspec.yaml
- test/src/channel_preview_test.dart
> Shadow ban

- lib/src/channel_preview.dart
- lib/src/message_actions_modal.dart
- lib/src/message_input.dart
- lib/src/message_reactions_modal.dart
- lib/src/message_widget.dart
- lib/src/sending_indicator.dart
- lib/src/stream_svg_icon.dart
Signed-off-by: Sahil Kumar <xdsahil@gmail.com>
> Message error state

- lib/src/message_input.dart
- test/src/channel_preview_test.dart
Allows 4 mentions at a time
(Added as separate PR)
> Only 4 mentions allowed at a time

- example/lib/main.dart
- lib/src/typing_indicator.dart
> feat: Added typing indicator design and styling fixes

- lib/src/message_input.dart
The permission modal is now better in line with the design
> fix: Fixed no permission modal

- example/lib/group_chat_details_screen.dart
- example/lib/new_chat_screen.dart
- example/lib/new_group_chat_screen.dart
- lib/src/channel_header.dart
- lib/src/channel_list_header.dart
- lib/src/info_tile.dart
- lib/src/message_list_view.dart
- lib/src/message_search_list_view.dart
- lib/src/stream_chat.dart
- lib/stream_chat_flutter.dart
> feat: Added info tile and wrapped channel list and channel header

- lib/src/image_footer.dart
- lib/src/message_list_view.dart
> feat: Added images for photos modal

- lib/src/channel_file_display_screen.dart
> fix: fixed media loading

- lib/src/channel_list_view.dart
- lib/src/stream_chat_theme.dart
> fix: fixed channel separator

- CHANGELOG.md
- lib/src/reaction_picker.dart
- pubspec.yaml
> Reactions Hotfix

- packages/flutter_widgets/example/lib/group_info_screen.dart
- packages/flutter_widgets/example/lib/main.dart
- packages/flutter_widgets/lib/src/channel_list_header.dart
- packages/flutter_widgets/lib/src/message_input.dart
- packages/flutter_widgets/lib/src/message_list_view.dart
- packages/flutter_widgets/lib/src/thread_header.dart
> Doc fixes 2

- packages/flutter_widgets/lib/src/image_footer.dart
> fix: Fixed modal crash

- packages/flutter_widgets/example/lib/chat_info_screen.dart
- packages/flutter_widgets/example/lib/group_info_screen.dart
- packages/flutter_widgets/lib/src/full_screen_media.dart
- packages/flutter_widgets/lib/src/giphy_attachment.dart
- packages/flutter_widgets/lib/src/image_actions_modal.dart
- packages/flutter_widgets/lib/src/image_attachment.dart
- packages/flutter_widgets/lib/src/image_footer.dart
- packages/flutter_widgets/lib/src/image_header.dart
- packages/flutter_widgets/lib/src/message_list_view.dart
- packages/flutter_widgets/lib/src/message_widget.dart
- packages/flutter_widgets/lib/src/video_attachment.dart
> Doc fixes 2.3

- packages/flutter_widgets/lib/src/file_attachment.dart
- packages/flutter_widgets/lib/src/message_input.dart
> fix: Added file size fix

- packages/dart_client/lib/src/api/channel.dart
- packages/dart_client/lib/src/models/channel_model.dart
- packages/dart_client/lib/src/models/message.dart
> [Message, ChannelModel] Add merge helper functions for easier data manipulation

- packages/dart_client/lib/src/client.dart
- packages/dart_client/test/src/client_test.dart
- packages/flutter_widgets/example/lib/notifications_service.dart
> [Flutter-SDK] Migrate to push enum

- packages/stream_chat_flutter_core/lib/src/channel_list_core.dart
- packages/stream_chat_flutter_core/lib/src/message_search_list_core.dart
- packages/stream_chat_flutter_core/lib/src/stream_chat_core.dart
- packages/stream_chat_flutter_core/lib/src/user_list_core.dart
- packages/stream_chat_flutter_core/lib/src/users_bloc.dart
- Update documentation 
- Sort required params first
> Update Core Documentation

- packages/flutter_widgets/lib/src/channel_list_view.dart
- packages/flutter_widgets/lib/src/message_search_list_view.dart
- packages/stream_chat_flutter_core/example/lib/main.dart
- packages/stream_chat_flutter_core/lib/src/channel_list_core.dart
- packages/stream_chat_flutter_core/lib/src/message_list_core.dart
- packages/stream_chat_flutter_core/lib/src/message_search_list_core.dart
- packages/stream_chat_flutter_core/lib/src/typedef.dart
- Use a standard typedef for error builder 
- Migrate breaking code 
- Fixed lint warning
> [Core] Use standard callback for ErrorBuilder 

- packages/stream_chat_flutter_core/lib/src/channel_list_core.dart
- packages/stream_chat_flutter_core/lib/src/channels_bloc.dart
- packages/stream_chat_flutter_core/lib/src/lazy_load_scroll_view.dart
- packages/stream_chat_flutter_core/lib/src/message_list_core.dart
- packages/stream_chat_flutter_core/lib/src/message_search_bloc.dart
- packages/stream_chat_flutter_core/lib/src/message_search_list_core.dart
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
- packages/stream_chat_flutter_core/lib/src/stream_chat_core.dart
- packages/stream_chat_flutter_core/lib/src/users_bloc.dart
- Add external API links for Blocs linking to their corresponding section on our website.
- Sort constructor first across core package
> Improve Core package docs

- packages/stream_chat_flutter_core/lib/src/channel_list_core.dart
- packages/stream_chat_flutter_core/lib/src/channels_bloc.dart
- packages/stream_chat_flutter_core/lib/src/lazy_load_scroll_view.dart
- packages/stream_chat_flutter_core/lib/src/message_list_core.dart
- packages/stream_chat_flutter_core/lib/src/message_search_bloc.dart
- packages/stream_chat_flutter_core/lib/src/message_search_list_core.dart
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
- packages/stream_chat_flutter_core/lib/src/stream_chat_core.dart
- packages/stream_chat_flutter_core/lib/src/user_list_core.dart
- packages/stream_chat_flutter_core/lib/src/users_bloc.dart
- Add `assert` checks to required parameters. 
- PR #245 should be merged first
> Add assert checks for required params

- packages/stream_chat/lib/src/api/channel.dart
> fix: granular scroll

- packages/stream_chat/lib/src/client.dart
> fixes #258: reset _connectCompleter on disconnect

- packages/stream_chat/lib/src/api/channel.dart
- packages/stream_chat/lib/src/attachment_file_uploader.dart
- packages/stream_chat/lib/src/client.dart
> [LLC -> AttachmentFileUploader] Add remaining delete methods

- packages/stream_chat/lib/src/api/channel.dart
- packages/stream_chat/lib/src/client.dart
- packages/stream_chat/lib/src/extensions/map_extension.dart
- packages/stream_chat/lib/src/models/channel_state.dart
- packages/stream_chat/lib/src/models/channel_state.g.dart
- packages/stream_chat/lib/src/models/message.dart
- packages/stream_chat/lib/src/models/message.g.dart
- packages/stream_chat/test/src/api/channel_test.dart
- packages/stream_chat/test/src/client_test.dart
- packages/stream_chat/test/src/models/channel_state_test.dart
- packages/stream_chat/test/src/models/message_test.dart
- packages/stream_chat_flutter_core/lib/src/message_search_bloc.dart
> Feat -> Pin Message

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/api/channel.dart
- packages/stream_chat/lib/src/models/attachment_file.dart
- packages/stream_chat/lib/src/models/attachment_file.freezed.dart
- packages/stream_chat/lib/src/models/attachment_file.g.dart
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/attachment_upload_state_builder.dart
- packages/stream_chat_flutter/lib/src/attachment/file_attachment.dart
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/pubspec.yaml
> Add `preparing` state to attachment upload state

- packages/stream_chat/lib/src/api/channel.dart
- packages/stream_chat/lib/src/db/chat_persistence_client.dart
- packages/stream_chat_flutter_core/README.md
- packages/stream_chat_persistence/example/ios/Runner.xcodeproj/project.pbxproj
- packages/stream_chat_persistence/example/ios/Runner.xcworkspace/contents.xcworkspacedata
- packages/stream_chat_persistence/example/lib/main.dart
- packages/stream_chat_persistence/example/pubspec.yaml
- packages/stream_chat_persistence/lib/src/dao/channel_query_dao.dart
- packages/stream_chat_persistence/lib/src/dao/dao.dart
- packages/stream_chat_persistence/lib/src/dao/pinned_message_dao.dart
- packages/stream_chat_persistence/lib/src/dao/pinned_message_dao.g.dart
- packages/stream_chat_persistence/lib/src/db/moor_chat_database.dart
- packages/stream_chat_persistence/lib/src/db/moor_chat_database.g.dart
- packages/stream_chat_persistence/lib/src/entity/entity.dart
- packages/stream_chat_persistence/lib/src/entity/messages.dart
- packages/stream_chat_persistence/lib/src/entity/pinned_messages.dart
- packages/stream_chat_persistence/lib/src/mapper/channel_mapper.dart
- packages/stream_chat_persistence/lib/src/mapper/mapper.dart
- packages/stream_chat_persistence/lib/src/mapper/pinned_message_mapper.dart
- packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart
- packages/stream_chat_persistence/pubspec.yaml
> [Persistence] Add support for pinned messages

- packages/stream_chat_flutter/lib/src/message_input.dart
> fix: Keyboard now closes when a command is enabled

- packages/stream_chat_flutter/lib/src/image_actions_modal.dart
Added new attachment delete logic
> fix: Delete now deletes a single image

- packages/stream_chat_flutter/lib/src/image_actions_modal.dart
- packages/stream_chat_flutter/lib/src/stream_chat_theme.dart
> fix: channel header text style

- packages/stream_chat/lib/src/api/channel.dart
- packages/stream_chat/lib/src/api/requests.dart
- packages/stream_chat/lib/src/client.dart
- packages/stream_chat/lib/src/db/chat_persistence_client.dart
- packages/stream_chat/lib/src/models/channel_state.dart
- packages/stream_chat/test/src/api/requests_test.dart
- packages/stream_chat/test/src/client_test.dart
- packages/stream_chat/test/version_test.dart
- packages/stream_chat_flutter/lib/src/channel_info.dart
- packages/stream_chat_flutter/lib/src/channel_list_view.dart
- packages/stream_chat_flutter_core/lib/src/channel_list_core.dart
- packages/stream_chat_flutter_core/lib/src/channels_bloc.dart
- packages/stream_chat_persistence/example/pubspec.yaml
- packages/stream_chat_persistence/lib/src/dao/channel_query_dao.dart
- packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart
> Add custom sort support for offline channels

- packages/stream_chat_flutter/lib/src/message_list_view.dart
expose `MessageLisView.systemMessageBuilder`
> feat(ui): system builder

- packages/stream_chat_flutter/lib/src/message_text.dart
> fix: Fixes line breaks 

- packages/stream_chat_flutter/example/lib/tutorial-part-6.dart
- packages/stream_chat_flutter/lib/src/channel_image.dart
- packages/stream_chat_flutter/lib/src/full_screen_media.dart
- packages/stream_chat_flutter/lib/src/image_footer.dart
- packages/stream_chat_flutter/lib/src/message_input.dart
- packages/stream_chat_flutter/lib/src/message_search_list_view.dart
- packages/stream_chat_flutter/lib/src/quoted_message_widget.dart
- packages/stream_chat_flutter/lib/src/video_thumbnail_image.dart
- packages/stream_chat_flutter/pubspec.yaml
- use share_plus plugin (the previous one wasn't maintained)
- update dependencies 
- minor fixes
> fix: pre release

- README.md
Update title link to Stream's Flutter landing page.
> fix: Update title link

- packages/stream_chat_flutter/lib/src/attachment/file_attachment.dart
- packages/stream_chat_flutter/lib/src/attachment/giphy_attachment.dart
- packages/stream_chat_flutter/lib/src/message_widget.dart
- packages/stream_chat_flutter/lib/src/utils.dart
> fix: attachment builder 

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view.dart
- packages/stream_chat_flutter/pubspec.yaml
> fix: unread count not updating while the chat is open

- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_persistence/pubspec.yaml
> fix: remove useless dependencies

- packages/stream_chat_flutter/lib/src/message_input.dart
> fix(UI-Kit): Show selected attachment file as file in message input

- packages/stream_chat/lib/src/api/websocket.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat/test/src/api/web_socket_stub_test.dart
- packages/stream_chat/test/src/api/websocket_test.dart
- removed conditional imports for web
- fix disconnection while connecting
- add test case
> fix: ws disconnection

- packages/stream_chat_flutter/lib/src/message_input.dart
Fixed sending button padding issue
> fix: Fixed sendingbutton.outside case

- packages/stream_chat_flutter/lib/src/full_screen_media.dart
- packages/stream_chat_flutter/lib/src/image_footer.dart
- packages/stream_chat_flutter/lib/src/image_header.dart
> fix: image gallery with ephemeral message

- packages/stream_chat_flutter/lib/src/channel_list_view.dart
- packages/stream_chat_flutter_core/lib/src/channels_bloc.dart
- packages/stream_chat_flutter_core/lib/src/lazy_load_scroll_view.dart
- packages/stream_chat_flutter_core/test/channel_list_core_test.dart
> fix: channel list pagination spinner

- packages/stream_chat_flutter/lib/src/message_input.dart
> fix: attachments upload when size exceeds

- packages/stream_chat_flutter/lib/src/default_mention_tile.dart
- packages/stream_chat_flutter/lib/src/mention_tile.dart
- packages/stream_chat_flutter/lib/src/message_input.dart
- packages/stream_chat_flutter/lib/src/message_list_view.dart
- packages/stream_chat_flutter/lib/src/stream_chat_theme.dart
- packages/stream_chat_flutter/lib/stream_chat_flutter.dart
> fix: message input

- packages/stream_chat_flutter/lib/src/message_list_view.dart
> feat: add onLinkTap

- packages/stream_chat/lib/src/client.dart
Fixed pinMessage functionality and add docs for it
> fix: pinMessage and add docs

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/channels_bloc.dart
- packages/stream_chat_flutter_core/pubspec.yaml
> fix: channels bloc does not perform the call if pagination ended

- packages/stream_chat_flutter_core/README.md
- [ x ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ x ] The code changes follow best practices
- [ x ] Code changes are tested (add some information if not applicable)
Update links in Core README
> chore(core): Readme update

- packages/stream_chat_flutter/lib/src/channel_name.dart
> feat: add textoverflow param to channel name

- packages/stream_chat/example/lib/main.dart
- packages/stream_chat/lib/src/api/channel.dart
> fix: performance

- packages/stream_chat/lib/src/models/filter.dart
- packages/stream_chat/test/src/models/filter_test.dart
the filter will be encoded like a group operator would
> fix: filter.operator can be null

- packages/stream_chat_flutter/lib/src/attachment/file_attachment.dart
- packages/stream_chat_flutter/lib/src/image_footer.dart
- packages/stream_chat_flutter/lib/src/message_input.dart
- packages/stream_chat_flutter/lib/src/video_service.dart
adds `MessageInput.maxAttachmentSize` and fixes file attachments in `MessageInput`
> feat: max attachment size

- packages/stream_chat/lib/src/api/channel.dart
- packages/stream_chat/lib/src/client.dart
- packages/stream_chat/test/src/api/channel_test.dart
- packages/stream_chat/test/src/client_test.dart
> fix: make timeoutOrExpirationDate optional

- packages/stream_chat_flutter/lib/src/channel_list_view.dart
Added callbacks for default slidable actions
> feat: Swipe actions

- packages/stream_chat_flutter/lib/src/message_input.dart
- packages/stream_chat_flutter/lib/src/message_widget.dart
> fix: message widget not update when message is updated

- packages/stream_chat_flutter/lib/src/user_list_view.dart
- packages/stream_chat_flutter_core/lib/src/user_list_core.dart
- packages/stream_chat_flutter_core/test/user_list_core_test.dart
> fix: user list error handling

- packages/stream_chat_flutter/lib/src/message_list_view.dart
> fix: nextMessage index

- docusaurus/docs/Flutter/stream_chat_flutter_core/channel_list_core.mdx
- docusaurus/docs/Flutter/stream_chat_flutter_core/channels_bloc.mdx
- docusaurus/docs/Flutter/stream_chat_flutter_core/message_list_core.mdx
- docusaurus/docs/Flutter/stream_chat_flutter_core/message_search_bloc.mdx
- docusaurus/docs/Flutter/stream_chat_flutter_core/message_search_list_core.mdx
- docusaurus/docs/Flutter/stream_chat_flutter_core/user_list_core.mdx
- docusaurus/docs/Flutter/stream_chat_flutter_core/users_bloc.mdx
Added background for core components
> Core fixes

- packages/stream_chat_flutter/lib/src/message_input.dart
> feat: message input error listener

- packages/stream_chat_flutter/lib/src/channel_list_view.dart
- packages/stream_chat_flutter_core/lib/src/channels_bloc.dart
- packages/stream_chat_flutter_core/lib/src/lazy_load_scroll_view.dart
- packages/stream_chat_flutter_core/lib/src/message_search_bloc.dart
- packages/stream_chat_flutter_core/lib/src/users_bloc.dart
> fix: channel pagination error retry

- docusaurus/docs/Flutter/basics/choose_package.mdx
- docusaurus/docs/Flutter/guides/_category_.json
- docusaurus/docs/Flutter/stream_chat_flutter/_category_.json
- docusaurus/docs/Flutter/stream_chat_flutter/message_list_view.mdx
- docusaurus/docs/Flutter/stream_chat_flutter/user_list_view.mdx
- docusaurus/docs/Flutter/stream_chat_flutter_core/_category_.json
- docusaurus/docs/Flutter/stream_chat_flutter_core/user_list_core.mdx
> fix: Core fixes and category position adjustments 

- docusaurus/docs/Flutter/basics/choose_package.mdx
- docusaurus/docs/Flutter/guides/adding_custom_attachments.mdx
- docusaurus/docs/Flutter/guides/migration_guide_2_0.mdx
> feat: Added mig guide (scf)

- docusaurus/docs/Flutter/guides/adding_custom_attachments.mdx
- docusaurus/docs/Flutter/guides/adding_local_data_persistence.mdx
- docusaurus/docs/Flutter/guides/adding_push_notifcations.mdx
- docusaurus/docs/Flutter/guides/migration_guide_2_0.mdx
> fix: removed intro and added detail fixes

- packages/stream_chat/lib/src/core/api/channel_api.dart
- packages/stream_chat/test/src/core/api/channel_api_test.dart
> fix(llc): channel.stopWatching

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/client.dart
> fix(llc): reverse user, event.me merge position

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view.dart
> fix(ui): add null-check in currentUserMember

- docusaurus/docs/Flutter/guides/adding_localization.mdx
- packages/stream_chat_flutter/example/lib/main.dart
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/README.md
- packages/stream_chat_localizations/lib/src/stream_chat_localizations.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_fr.dart
- Support for Spanish
- Fix some typos in French
> feat(localization): Support for Spanish

- README.md
> chore(repo): Fix sample app link in README

- .github/workflows/pr_title.yml
This is a [Github Action](https://github.com/GetStream/verify-semantic-changelog-update) that ensures your PR contains a changelog entry for all the user facing changes.
The action works without configuration, however you can provide options for customization.
```yml
with:
types: |
fix
feat
scopes: |
{
"llc": "packages/stream_chat",
"ui": "packages/stream_chat_flutter",
"core": "packages/stream_chat_flutter_core",
"localization": "packages/stream_chat_flutter_localizations",
"persistence": "packages/stream_chat_persistence"
}
path: |
changelog.md
```
> ci(repo): add verify-semantic-changelog-update action workflow

- packages/stream_chat_flutter/lib/src/channel_avatar.dart
- packages/stream_chat_flutter/lib/src/channel_header.dart
- packages/stream_chat_flutter/lib/src/channel_list_view.dart
- packages/stream_chat_flutter/lib/src/channel_preview.dart
- packages/stream_chat_flutter/lib/src/message_input.dart
- packages/stream_chat_flutter/lib/src/message_list_view.dart
- packages/stream_chat_flutter/lib/src/message_widget.dart
- packages/stream_chat_flutter/lib/src/reaction_picker.dart
- packages/stream_chat_flutter/lib/src/thread_header.dart
This fixes broken links to images in our code documentation.
> docs(doc): fix image file paths

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/client.dart
- packages/stream_chat/lib/src/core/models/own_user.dart
- packages/stream_chat/lib/src/core/models/own_user.g.dart
- packages/stream_chat/test/src/client/client_test.dart
> fix(llc): Fix unread count not updating when the current user is set.

- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/channel_list_core.dart
- packages/stream_chat_flutter_core/lib/src/message_search_list_core.dart
- packages/stream_chat_flutter_core/lib/src/user_list_core.dart
- packages/stream_chat_flutter_core/test/message_search_bloc_test.dart
- packages/stream_chat_flutter_core/test/message_search_list_core_test.dart
> fix(core): match oldWidget custom type params using jsonEncode in didUpdate.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/giphy_attachment.dart
- packages/stream_chat_flutter/lib/src/image_group.dart
- packages/stream_chat_flutter/lib/src/message_widget.dart
> fix(ui): Attachment tap fix

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input.dart
> fix(ui): fix `MessageInput` rendering errors

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view.dart
- packages/stream_chat_flutter/test/src/message_list_view_test.dart
> fix(ui): check scrollController is attached before calling jump.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view.dart
> fix(ui): thread reply scrolling main list

- packages/stream_chat/test/src/client/channel_test.dart
- packages/stream_chat/test/src/client/client_test.dart
- packages/stream_chat/test/src/core/api/attachment_file_uploader_test.dart
- packages/stream_chat_flutter/test/scrollable_positioned_list/horizontal_scrollable_positioned_list_test.dart
- packages/stream_chat_flutter/test/scrollable_positioned_list/reversed_scrollable_positioned_list_test.dart
- packages/stream_chat_flutter/test/scrollable_positioned_list/scrollable_positioned_list_test.dart
- packages/stream_chat_flutter/test/scrollable_positioned_list/separated_scrollable_positioned_list_test.dart
- packages/stream_chat_flutter/test/scrollable_positioned_list/seperated_horizontal_scrollable_positioned_list_test.dart
- packages/stream_chat_flutter_core/test/channels_bloc_test.dart
Fixes mocktail breaking changes
> fix(ui, llc, core): fix tests

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/gallery_footer.dart
- packages/stream_chat_flutter/lib/src/message_list_view.dart
> feat(ui): Added better spacing builder

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/api/requests.dart
- packages/stream_chat/lib/src/core/api/requests.g.dart
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
Added queryAround implementation
> feat(llc, ui): Added a queryAround implementation

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/scrollable_positioned_list/src/positioned_list.dart
- packages/stream_chat_flutter/lib/scrollable_positioned_list/src/scroll_view.dart
- packages/stream_chat_flutter/lib/scrollable_positioned_list/src/scrollable_positioned_list.dart
- packages/stream_chat_flutter/lib/src/message_input.dart
- packages/stream_chat_flutter/lib/src/message_list_view.dart
- packages/stream_chat_flutter_core/test/channel_list_core_test.dart
- packages/stream_chat_flutter_core/test/message_search_list_core_test.dart
- packages/stream_chat_flutter_core/test/stream_channel_test.dart
- packages/stream_chat_flutter_core/test/user_list_core_test.dart
> fix(ui): fix for unfocusing bug

- packages/stream_chat/example/lib/main.dart
- packages/stream_chat_flutter/example/lib/tutorial_part_6.dart
- packages/stream_chat_flutter_core/example/lib/main.dart
- packages/stream_chat_localizations/example/lib/add_new_lang.dart
- packages/stream_chat_persistence/example/lib/main.dart
> chore(repo): add missed trailing commas

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input.dart
> fix(ui): do not use `withData: true` property

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/client/client.dart
> fix(llc): totalUnreadCount is not updating when app is resumed from background mode

- packages/stream_chat_flutter_core/pubspec.yaml
> fix(core): update connectivity dep

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/giphy_attachment.dart
- packages/stream_chat_flutter/lib/src/attachment/image_attachment.dart
- packages/stream_chat_flutter/lib/src/attachment/video_attachment.dart
- packages/stream_chat_flutter/lib/src/full_screen_media.dart
> feat(ui): added autoplay to videos

- packages/stream_chat/lib/src/core/models/event.dart
- packages/stream_chat/lib/src/core/models/own_user.dart
- packages/stream_chat/lib/src/core/models/user.dart
The PR update some comments to make them follow the Effective Dart documentation guidelines. It also fixes some typos.
> chore(repo): make comments follow dart guidelines and fix typos

- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/channels_bloc.dart
- packages/stream_chat_flutter_core/lib/src/message_search_bloc.dart
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
- packages/stream_chat_flutter_core/lib/src/stream_controller_extension.dart
- packages/stream_chat_flutter_core/lib/src/users_bloc.dart
> fix(core): fixed bad state on calling streamController.add

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input.dart
> fix(ui): fix cast error while compressing video.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
> fix(llc): thread message deletion

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
> fix(llc): fix ownReactions population

- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/README.md
- packages/stream_chat_localizations/example/ios/Runner/Info.plist
- packages/stream_chat_localizations/example/lib/main.dart
- packages/stream_chat_localizations/example/lib/override_lang.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_pt.dart
- packages/stream_chat_localizations/pubspec.yaml
Added Portuguese translations + updated language references in localization example project
> feat(localization): added support for Portuguese language

- packages/stream_chat_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/stream_chat_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
This PR includes minor changes to the macos xcode project for the sample app for `stream_chat_flutter`. These changes are a result of building the sample app for macos.
> build(ui): minor xcode updates to run example on macos

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input.dart
- packages/stream_chat_flutter/lib/src/message_text.dart
> fix(ui): fix `unban` command not working in `MessageInput`.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/http/interceptor/auth_interceptor.dart
> fix(llc): add type check in auth_interceptor.dart

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/client.dart
- packages/stream_chat/lib/src/core/api/requests.dart
- packages/stream_chat/lib/src/core/api/requests.g.dart
- packages/stream_chat/lib/src/core/api/user_api.dart
- packages/stream_chat/lib/src/core/models/channel_state.g.dart
- packages/stream_chat/test/src/client/client_test.dart
- packages/stream_chat/test/src/core/api/user_api_test.dart
Fixes: https://getstream.zendesk.com/agent/tickets/17927
> feat(llc): add support for `partialUserUpdate` endpoint.

- packages/stream_chat_flutter/lib/src/full_screen_media.dart
- Reduce build calls
- Add intervals/curves to improve the animation feel
- Expose controllers
> perf(ui): improve full screen media animation

- packages/stream_chat_flutter/example/android/app/build.gradle
- packages/stream_chat_flutter/example/android/app/src/main/AndroidManifest.xml
- packages/stream_chat_flutter/example/android/build.gradle
- packages/stream_chat_flutter/example/pubspec.yaml
> fix(ui): sample app version bump

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
> fix(llc): member removed

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
> fix(llc): Hard delete from dashboard does not delete message from client

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view.dart
- packages/stream_chat_flutter/pubspec.yaml
There have been multiple reports from customers who are facing UI issues because of the error thrown from the visibility detector package that we use. In this PR, we replace the visibility detector package and assign the responsibility of that logic to ItemPositionsListener of the scrollable_positioned_list.
> fix(ui): Remove Visibility Detector Package

- packages/stream_chat_flutter/CHANGELOG.md
Added the updates for live event improvements in the changelog
> Added the updates in changelog

- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter/test/src/attachment_actions_modal_test.dart
- packages/stream_chat_flutter/test/src/theme/gallery_header_theme_test.dart
Fixed failing tests for gallery header and attachment actions
> fix(ui): Fixed failing tests for attachment actions and gallery header

- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/README.md
- packages/stream_chat_localizations/lib/src/stream_chat_localizations.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_de.dart
- packages/stream_chat_localizations/test/override_test.dart
> feat(localization): add German localization

- .github/workflows/dart_code_metrics.yaml
- docusaurus/docs/Flutter/guides/error_reporting_with_sentry.mdx
> docs(doc): add sentry guide

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/event_type.dart
> feat(llc): handle member.updated events in channel client

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/core/models/channel_model.dart
- packages/stream_chat/lib/src/core/models/channel_model.g.dart
- packages/stream_chat/lib/src/core/models/event.dart
- packages/stream_chat/lib/src/core/models/event.g.dart
- packages/stream_chat/lib/src/core/models/own_user.dart
- packages/stream_chat/lib/src/core/models/user.dart
- packages/stream_chat/test/src/client/client_test.dart
- packages/stream_chat/test/src/core/models/channel_test.dart
> feat(llc): create disabled, hidden, truncatedAt a field in channel

- .github/workflows/stream_flutter_workflow.yml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/example/android/app/src/main/kotlin/com/example/example/Application.kt
- packages/stream_chat_flutter/lib/src/utils.dart
> fix(ui): fix file download

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
> chore(ui): Updated photo_view to 0.14.0

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_widget.dart
> feat(ui): animate pinned message color

- packages/stream_chat/lib/src/core/models/user.dart
User extra data "name" key can be set to null; this PR adds a check to validate.
> fix(llc): handle user extra data name null condition

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/v4/scroll_view/channel_scroll_view/stream_channel_list_tile.dart
> fix(ui): Fix `ChannelListTile` sendingIndicator `isMessageRead` calculations

- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/README.md
- packages/stream_chat_localizations/lib/src/stream_chat_localizations.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_no.dart
feat: Added the Norwegian translation for the Stream Chat
- [x ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x ] The code changes follow best practices
I copied and pasted the english version of the language translations and translated directly between the apostrophes.
> feat(localization): Create stream_chat_localizations_no.dart 

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view.dart
> fix(ui): fix date divider not showing

- packages/stream_chat/lib/src/core/models/attachment_file.dart
- packages/stream_chat/lib/src/core/models/attachment_file.freezed.dart
- packages/stream_chat/lib/src/core/models/attachment_file.g.dart
- packages/stream_chat/lib/src/db/chat_persistence_client.dart
- packages/stream_chat/test/fixtures/attachment_file.json
- packages/stream_chat/test/src/core/models/attachment_file_test.dart
- packages/stream_chat_flutter/lib/src/attachment/attachment_handler/desktop_attachment_handler.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_attachment_picker.dart
> fix(llc, ui): copy file to tempdir before uploading a file and do not serialize bytes

- docusaurus/docs/Flutter/guides/initialize_stream_chat_widget_tree.mdx
- [ x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ x] The code changes follow best practices
- [ x] Code changes are tested (add some information if not applicable)
Added a guide to initialize Stream Chat Flutter in a part of the widget tree and to delay connection when needed.
> docs(doc): add guide to initialize stream chat

- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel_list_controller.dart
- packages/stream_chat_flutter_core/lib/src/stream_user_list_controller.dart
> fix(core): StreamChannelListView load more indicator non stop.

- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel_list_controller.dart
Fixes: https://getstream.zendesk.com/agent/tickets/26439
> feat(core): Add `ChannelListController.filter` and `ChannelListController.sort` setters.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/file_attachment.dart
- packages/stream_chat_flutter/lib/src/attachment/image_attachment.dart
- packages/stream_chat_flutter/lib/src/extension.dart
- packages/stream_chat_flutter/lib/src/full_screen_media.dart
- packages/stream_chat_flutter/lib/src/image_group.dart
- packages/stream_chat_flutter/lib/src/media_list_view.dart
- packages/stream_chat_flutter/lib/src/message_widget.dart
- packages/stream_chat_flutter/lib/src/v4/message_input/stream_attachment_picker.dart
- packages/stream_chat_flutter/lib/src/v4/message_input/stream_message_input.dart
- packages/stream_chat_flutter/lib/stream_chat_flutter.dart
- Fixes an error where Stream CDN images were not being resized in the message list view.
- Automatically resize images that are above a specific pixel count to ensure resizing works: https://getstream.io/chat/docs/go-golang/file_uploads/#image-resizing
- We should consider resizing all images before uploading - as a default behavior. This will require collaboration with the other frontend SDKs, and discussion is under way.
- TODOs are added for future follow-up.
> feat(ui): improve image resizing

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/client.dart
Fixes: https://getstream.zendesk.com/agent/tickets/25465
> fix(llc): only start listening to client event once connected.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/client/client.dart
- packages/stream_chat/test/src/client/channel_test.dart
- packages/stream_chat/test/src/fakes.dart
> fix(llc): channel clean up after dispose from cache

- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/lib/src/db/shared/native_db.dart
- packages/stream_chat_persistence/lib/src/db/shared/unsupported_db.dart
- packages/stream_chat_persistence/lib/src/db/shared/web_db.dart
- packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart
- packages/stream_chat_persistence/pubspec.yaml
Version 5.0.0 should include changes from [4.4.0](#440) but it doesn't have indexedDB, so this PR brings this back
> fix(persistence): bring back experimental indexedDB on web

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
> feat(ui): expose widthFactor in MessageWidget

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/keyboard_shortcuts/keyboard_shortcut_runner.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
[fix(ui): Show message custom actions on desktop context menu.](https://github.com/GetStream/stream-chat-flutter/commit/8ee32441a1262ce8085888d50c35afcfb6395ddf)
[fix(ui): don't handle keyboard shortcut when callback is null.](https://github.com/GetStream/stream-chat-flutter/commit/f3209e1805ec505b80ad78d7bf312a1d50eb8098)
> feat(ui): show custom action on context menu

- docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_4_0.mdx
- docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_5_0.mdx
> docs(doc): revert migration guides back to original slugs

- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_channel_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_member_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_message_search_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_user_list_controller.mdx
- docusaurus/docs/Flutter/05-guides/09-initialize_stream_chat_widget_tree.mdx
- docusaurus/flutter_versioned_docs/version-4.x.x/Flutter/stream_chat_flutter_core/stream_channel_list_controller.mdx
- docusaurus/flutter_versioned_docs/version-4.x.x/Flutter/stream_chat_flutter_core/stream_message_search_list_controller.mdx
- docusaurus/flutter_versioned_docs/version-4.x.x/Flutter/stream_chat_flutter_core/stream_user_list_controller.mdx
> docs(doc): fix broken links

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
Resolves https://github.com/GetStream/stream-chat-flutter/issues/1380
> chore(ui): upgrade lottie to v2

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
Resolves https://github.com/getstream/stream-chat-flutter/issues/1386, https://github.com/getstream/stream-chat-flutter/issues/1375, and https://github.com/GetStream/stream-chat-flutter/issues/1372
> chore(ui): update desktop drop dependency

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/pubspec.yaml
Resolves https://github.com/getstream/stream-chat-flutter/issues/1359
> chore(core): update connectivity plus dependency

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/example/lib/main.dart
- packages/stream_chat_flutter/lib/src/attachment_actions_modal/attachment_actions_modal.dart
- packages/stream_chat_flutter/lib/src/fullscreen_media/fsm_enums.dart
Resolves https://github.com/GetStream/stream-chat-flutter/issues/1347
> fix(ui): on reply callback not used in AttachmentActionsModal

- packages/stream_chat_flutter/test/src/attachment_actions_modal/attachment_actions_modal_test.dart
> test(ui): fix attachment actions modal test

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/api/device_api.dart
- packages/stream_chat/test/src/core/api/device_api_test.dart
Add Huawei and Xiaomi PushProvider values
fix #1403
> feat(llc): Add Huawei and Xiaomi PushProviders

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/example/linux/flutter/generated_plugin_registrant.cc
- packages/stream_chat_flutter/example/linux/flutter/generated_plugins.cmake
- packages/stream_chat_flutter/pubspec.yaml
Resolves https://github.com/getstream/stream-chat-flutter/issues/1344, https://github.com/getstream/stream-chat-flutter/issues/1352, and https://github.com/getstream/stream-chat-flutter/issues/1360
> chore(ui): update dart_vlc dependency

- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/README.md
- packages/stream_chat_localizations/lib/src/stream_chat_localizations.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_ca.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
Add Catalan to localizations.
Also managed to fix some weird Spanish translations.
> feat(localization): add catalan

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/pubspec.yaml
> chore(llc): update rate_limiter to ^1.0.0

- packages/stream_chat_localizations/lib/src/stream_chat_localizations_pt.dart
Adding an article to one sentence. And fixing a small grammar mistake in another one.
> Adding articel and fixing gramar mistake.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/localization/translations.dart
- packages/stream_chat_flutter/lib/src/scroll_view/photo_gallery/stream_photo_gallery.dart
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/example/lib/add_new_lang.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_ca.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_de.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_en.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_fr.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_it.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_ja.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_ko.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_no.dart
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_pt.dart
#1431 
Fixed labels related to empty attachments.
> fix(ui,localization): change label displayed when there is no photo or videos to attach

- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/lib/src/stream_chat_localizations_ca.dart
Changed some copies to be more precise with some expressions.
> fix(localization): update some copies due to correctness

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/event_type.dart
Listening for events `user.watching.start` and `user.watching.stop` and adding data to `ChannelState.watchersStream`
> fix(llc): Fixing watchers stream [ISSUE-1432] 

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/gallery/gallery_footer.dart
- packages/stream_chat_flutter/pubspec.yaml
> chore(ui): update share_plus dependency

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/gallery/gallery_footer.dart
Fixes this flutter issue: https://github.com/flutter/flutter/issues/47220. The solution is taken from the discussion of the issue.
> fix(ui): Support iPad for share button

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager.dart
- ~[ ] Code changes are tested (add some information if not applicable)~
Fixing a typo in imports
> fix(ui): Fixing typo in import

- docusaurus/docs/Flutter/05-guides/09-initialize_stream_chat_widget_tree.mdx
> Fix link in 05-guides/09-initialize_stream_chat_widget_tree

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/utils/extensions.dart
- packages/stream_chat_flutter/test/src/utils/extension_test.dart
> fix(ui): fix emoji regexp to exclude non-emoji chars

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
> feat(ui): Added `StreamMessageInput.ogPreviewFilter` to allow users to filter out the og preview links.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/url_attachment.dart
- packages/stream_chat_flutter/lib/src/message_input/quoted_message_widget.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_card.dart
- packages/stream_chat_flutter/lib/src/theme/message_theme.dart
- packages/stream_chat_flutter/lib/src/theme/stream_chat_theme.dart
- packages/stream_chat_flutter/test/src/theme/message_theme_test.dart
> feat(ui): add support for url attachment theming.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/models/own_user.dart
- packages/stream_chat/lib/stream_chat.dart
- packages/stream_chat/test/src/core/models/own_user_test.dart
> feat(llc): expose `ChannelMute` class.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_widget/message_widget_content.dart
> fix(ui): `UserAvatarTransform.userAvatarBuilder` works only for other user.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
> feat(ui): add support for customizing messageInput hint.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/client/client.dart
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
- packages/stream_chat_flutter_core/lib/src/stream_channel_list_event_handler.dart
> fix(llc, core): Fix issues related to channel mute.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/quoted_message_widget.dart
- packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart
- packages/stream_chat_flutter/lib/src/message_widget/bottom_row.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
- packages/stream_chat_flutter/lib/src/message_widget/quoted_message.dart
> fix(llc, ui): fix removing message not removing quoted reference.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart
> fix(ui): fix messages grouped incorrectly w.r.t. timestamp.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/url_attachment.dart
> fix(ui): handle image load error for url attachments.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/example/pubspec.yaml
- packages/stream_chat_flutter/lib/src/autocomplete/stream_autocomplete.dart
fix for https://github.com/GetStream/stream-chat-flutter/issues/1570 https://github.com/GetStream/stream-chat-flutter/issues/1498
Follows changes from https://github.com/GetStream/stream-chat-flutter/pull/1571 to also include custom autocomplete, not only ready-to-use user mentions
> fix(ui): autocomplete clicks on web

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/giphy_attachment.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
- packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
> fix(ui, core): fix various `StreamMessageListView` issues.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
> chore(ui): bump image_gallery_saver to 2.0.1.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/error/stream_chat_error.dart
- packages/stream_chat/lib/src/core/http/interceptor/auth_interceptor.dart
- packages/stream_chat/lib/src/core/http/interceptor/logging_interceptor.dart
- packages/stream_chat/lib/src/core/http/stream_chat_dio_error.dart
- packages/stream_chat/lib/src/core/http/stream_http_client.dart
- packages/stream_chat/lib/stream_chat.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat/test/src/core/error/stream_chat_error_test.dart
- packages/stream_chat/test/src/core/http/interceptor/auth_interceptor_test.dart
- packages/stream_chat/test/src/core/http/stream_chat_dio_error_test.dart
- packages/stream_chat/test/src/core/http/stream_http_client_test.dart
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
- packages/stream_chat_flutter_core/test/stream_channel_test.dart
> chore(llc, core, ui): bump `dio` to `^5.2.0`.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/client/client.dart
- packages/stream_chat/lib/src/db/chat_persistence_client.dart
- packages/stream_chat/test/src/client/client_test.dart
- packages/stream_chat/test/src/db/chat_persistence_client_test.dart
- packages/stream_chat/test/src/mocks.dart
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/lib/src/stream_chat_persistence_client.dart
- packages/stream_chat_persistence/test/stream_chat_persistence_client_test.dart
Fixes: GetStream/stream-flutter-planning#11
> feat(llc, persistence): add support for open and close persistence via client.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/client.dart
- packages/stream_chat/lib/src/event_type.dart
> fix(llc): Remove cached channel once left.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/bottom_sheets/stream_channel_info_bottom_sheet.dart
> fix(ui): fix `StreamChannelInfoBottomSheet` member list rendering.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart
> fix(ui): fix scrollController not working correctly for unread.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/quoted_message_widget.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_card.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget_content.dart
- packages/stream_chat_flutter/lib/src/message_widget/quoted_message.dart
> feat(ui): added support for `quotedMessageBuilder`.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
> fix(ui): fix attachment picker not able to find streamChatTheme.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/test/src/client/channel_test.dart
> fix(llc): handle channel mute expiration.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/avatars/group_avatar.dart
- packages/stream_chat_flutter/lib/src/avatars/user_avatar.dart
- packages/stream_chat_flutter/lib/src/channel/stream_channel_avatar.dart
> feat(ui): add support for builder to override avatars in StreamChannelAvatar.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_message_text_field.dart
> feat(ui): add support for `StreamMessageInput.contentInsertionConfiguration`.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/video_attachment.dart
- packages/stream_chat_flutter/lib/src/gallery/gallery_footer.dart
- packages/stream_chat_flutter/lib/src/message_input/quoted_message_widget.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input_attachment_list.dart
- packages/stream_chat_flutter/lib/stream_chat_flutter.dart
> feat(ui): add support for customizing message input attachments.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/attachment/handler/stream_attachment_handler_io.dart
> fix(ui): save attachments to gallery.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_widget/message_card.dart
> fix(ui): fix MessageWidget.widthFactor not working on web/desktop.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/pubspec.yaml
* chore(repo): remove deprecated code. by @xsahil03x in https://github.com/GetStream/stream-chat-flutter/pull/1675
* feat(ui): add support for `StreamMessageInput.contentInsertionConfiguration`. by @xsahil03x in [`61948d5` (#1671)](https://github.com/GetStream/stream-chat-flutter/pull/1671/commits/61948d512cd611e91f261b76a9e81bb6cdbb1629)
* chore(ui): bump jiffy to v6.2.1. by @xsahil03x in https://github.com/GetStream/stream-chat-flutter/commit/79faac57e5761296f0bf93719a57985758db9629
> Release: v7.0.0-beta.1

- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart
> fix(persistence): fix column `message.state` not found.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/models/message.dart
- packages/stream_chat/lib/src/core/models/message.g.dart
- packages/stream_chat/test/fixtures/channel_state_to_json.json
- packages/stream_chat/test/fixtures/message_to_json.json
> feat(llc): add support for setting message.type.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/pubspec.yaml
* Included changes from https://github.com/GetStream/stream-chat-flutter/releases/tag/6.8.0
> Release: v7.0.0-beta.2

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/test/src/core/http/interceptor/additional_headers_interceptor_test.dart
- packages/stream_chat/test/src/core/http/interceptor/auth_interceptor_test.dart
- packages/stream_chat/test/src/core/http/interceptor/connection_id_interceptor_test.dart
> feat(llc): add support for `channel.countUnreadMentions()`.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/attachment_picker/stream_attachment_picker.dart
- packages/stream_chat_flutter/lib/src/message_input/attachment_picker/stream_attachment_picker_bottom_sheet.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
Fixes: https://getstream.zendesk.com/agent/tickets/39933
> feat(ui): Add support for listening errors in AttachmentPicker.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
- packages/stream_chat_flutter/lib/src/utils/typedefs.dart
> feat(ui): allow override reactions tap.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/models/message.dart
- packages/stream_chat/lib/src/core/models/message.g.dart
> fix(llc): fix not able to update message with `type: reply`.

- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
- packages/stream_chat_flutter_core/lib/src/typedef.dart
Fixes: https://getstream.zendesk.com/agent/tickets/40750
> feat(core): add support for `StreamChannel.loadingBuilder` and `.errorBuilder`.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/attachment_picker/stream_attachment_picker.dart
> fix(ui): allowedAttachmentPickerTypes not working on mobile devices.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/models/attachment_file.dart
> fix(llc): fix not able to upload attachmentFile without name.

- .github/workflows/docusaurus.yml
- .github/workflows/legacy_version_analyze.yml
- .github/workflows/pana.yml
- .github/workflows/stream_flutter_workflow.yml
- .github/workflows/vale-doc-lint.yml
- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/models/attachment_file.dart
- packages/stream_chat/lib/src/core/models/message.dart
- packages/stream_chat/lib/src/core/models/message.g.dart
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/example/macos/Runner.xcodeproj/project.pbxproj
- packages/stream_chat_flutter/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/stream_chat_flutter/lib/src/message_input/attachment_picker/stream_attachment_picker.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget_content.dart
- packages/stream_chat_flutter/lib/src/message_widget/reactions/desktop_reactions_builder.dart
- packages/stream_chat_flutter/lib/src/message_widget/reactions/reaction_indicator.dart
- packages/stream_chat_flutter/lib/src/utils/typedefs.dart
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/lib/src/stream_channel.dart
- packages/stream_chat_flutter_core/lib/src/typedef.dart
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/pubspec.yaml
* fix(llc): fix not able to update message with `type: reply`. by @xsahil03x in https://github.com/GetStream/stream-chat-flutter/pull/1718
* chore(repo): bump actions/checkout from 3 to 4 by @dependabot in https://github.com/GetStream/stream-chat-flutter/pull/1725
* feat(ui): added support for `MessageWidget.onReactionsHover`. by @kanat in https://github.com/GetStream/stream-chat-flutter/pull/1722
* feat(core): add support for `StreamChannel.loadingBuilder` and `.errorBuilder`. by @xsahil03x in https://github.com/GetStream/stream-chat-flutter/pull/1728
* fix(ui): allowedAttachmentPickerTypes not working on mobile devices. by @xsahil03x in https://github.com/GetStream/stream-chat-flutter/pull/1727
* fix(llc): fix not able to upload attachmentFile without name. by @xsahil03x in …
> Release: v6.10.0

- docusaurus/docs/Flutter/05-guides/09-initialize_stream_chat_widget_tree.mdx
> fix(doc): update the use of GoRouter in the guides

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/pubspec.yaml
> Release: v6.12.0

- .github/workflows/pana.yml
> chore(repo): switch pana workflow to use new action

- packages/stream_chat/pubspec.yaml
> chore(llc): bump UUID dependency

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/pubspec.yaml
> chore(repo): bump patch version

- .github/workflows/dispatch_workflows.yml
- .github/workflows/docusaurus.yml
- .github/workflows/legacy_version_analyze.yml
- .github/workflows/pr_title.yml
- .github/workflows/stream_flutter_workflow.yml
Remove the `develop` branch logic in GH actions
> chore(repo): update pipelines to adhere to master branch

- docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_7_0.mdx
> feat(doc): add v7 migration guide

- docusaurus/docs/Flutter/02-stream_chat_flutter/03-custom_widgets/05-customize_attachment_picker_modal.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/03-custom_widgets/06-autocomplete_triggers.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/04-channel_list/stream_channel_list_header.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/04-channel_list/stream_channel_list_view.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/06-message_list/stream_message_list_view.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/06-message_list/stream_message_search_list_view.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/07-message_composer/stream_message_input.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/08-member_list/stream_member_list_view.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/09-user_list/stream_user_list_view.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_channel_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_member_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_message_input_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_message_search_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_user_list_controller.mdx
- docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_4_0.mdx
- docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_5_0.mdx
- docusaurus/docs/Flutter/05-guides/09-initialize_stream_chat_widget_tree.mdx
> fix(doc): fix inner links to the restructured pages

- packages/stream_chat/example/android/app/build.gradle
- packages/stream_chat/example/android/build.gradle
- packages/stream_chat/example/ios/Flutter/AppFrameworkInfo.plist
- packages/stream_chat/example/ios/Runner.xcodeproj/project.pbxproj
- packages/stream_chat/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/stream_chat/example/ios/Runner/Info.plist
- packages/stream_chat/example/pubspec.yaml
- packages/stream_chat_flutter/example/android/build.gradle
- packages/stream_chat_flutter/example/pubspec.yaml
- packages/stream_chat_flutter_core/example/android/app/build.gradle
- packages/stream_chat_flutter_core/example/android/build.gradle
- packages/stream_chat_flutter_core/example/ios/Flutter/AppFrameworkInfo.plist
- packages/stream_chat_flutter_core/example/ios/Runner.xcodeproj/project.pbxproj
- packages/stream_chat_flutter_core/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/stream_chat_flutter_core/example/ios/Runner/Info.plist
- packages/stream_chat_flutter_core/example/pubspec.yaml
- packages/stream_chat_localizations/example/android/build.gradle
- packages/stream_chat_localizations/example/ios/Flutter/AppFrameworkInfo.plist
- packages/stream_chat_localizations/example/ios/Runner.xcodeproj/project.pbxproj
- packages/stream_chat_localizations/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/stream_chat_localizations/example/ios/Runner/Info.plist
- packages/stream_chat_localizations/example/pubspec.yaml
- packages/stream_chat_persistence/example/android/build.gradle
- packages/stream_chat_persistence/example/ios/Flutter/AppFrameworkInfo.plist
- packages/stream_chat_persistence/example/ios/Runner.xcodeproj/project.pbxproj
- packages/stream_chat_persistence/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- packages/stream_chat_persistence/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/stream_chat_persistence/example/ios/Runner/Info.plist
- packages/stream_chat_persistence/example/pubspec.yaml
Update SDK dependencies in all example projects
> chore(repo): update SDK dependencies in all example projects

- .github/workflows/close-inactive-issues.yml
We need an automated way to check for issues that are stale, so we can prioritise accordingly.
> chore(repo): house keeping action for issues and PRs

- docusaurus/docs/Flutter/02-stream_chat_flutter/03-custom_widgets/01-customize_message_widget.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/lazy_load_scroll_view.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/message_list_core.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/paged_value_listenable_builder.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_channel_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_channel_list_event_handler.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_chat_core.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_member_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_message_input_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_message_search_list_controller.mdx
- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_user_list_controller.mdx
- docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_7_0.mdx
> docs(repo): add migration guide for customAttachmentBuilder removal + restructuring

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
Updated `photo_manager` dependency to `^3.0.0`
> chore(ui): update photo_manager dependency to 3.0.0

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/example/pubspec.yaml
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/example/pubspec.yaml
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/example/pubspec.yaml
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/example/pubspec.yaml
- packages/stream_chat_localizations/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/example/pubspec.yaml
- packages/stream_chat_persistence/pubspec.yaml
7.3.0 release for the Stream Chat Flutter SDK
> release: v7.3.0

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/client.dart
> fix(llc): fixed user parsing leading to incorrect online presence

- docusaurus/docs/Flutter/04-stream_chat_flutter_core/stream_message_search_list_controller.mdx
> docs(core): simple doc fix for search list controller

- .github/workflows/docusaurus.yml
> fix(doc): documentation workflow

- docusaurus/docs/Flutter/02-stream_chat_flutter/getting_started.mdx
- docusaurus/docs/Flutter/02-stream_chat_flutter/stream_chat_and_theming.mdx
> doc: small doc fixes

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/version.dart
- packages/stream_chat/pubspec.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_flutter_core/CHANGELOG.md
- packages/stream_chat_flutter_core/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/pubspec.yaml
- packages/stream_chat_persistence/CHANGELOG.md
- packages/stream_chat_persistence/pubspec.yaml
> release: v8.1.0

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/stream_chat.dart
Fixed localisation with country codes for jiffy.
> fix(llc): fixed locales

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_widget_content.dart
onThreadTap has been added in MessageWidgetContent to enable thread tap action.
> fix(ui): onThreadTap has been added in MessageWidgetContent to enable thread tap action.

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/ai_assistant/ai_typing_indicator_view.dart
- packages/stream_chat_flutter/lib/src/ai_assistant/stream_typewriter_builder.dart
- packages/stream_chat_flutter/lib/src/ai_assistant/streaming_message_view.dart
- packages/stream_chat_flutter/lib/src/message_widget/message_text.dart
- packages/stream_chat_flutter/lib/src/misc/markdown_message.dart
- packages/stream_chat_flutter/lib/stream_chat_flutter.dart
- packages/stream_chat_flutter/test/src/ai_assistant/ai_typing_indicator_view_test.dart
- packages/stream_chat_flutter/test/src/ai_assistant/streaming_message_view_test.dart
This pull request introduces several new widgets and refactors existing code to enhance the AI assistant features in the `stream_chat_flutter` package. The main additions include new widgets for displaying AI typing indicators, typewriter-style text animations, and streaming message views. Additionally, there are refactors to integrate these new components seamlessly into the existing codebase.
New Widgets and Components:
* [`packages/stream_chat_flutter/lib/src/ai_assistant/ai_typing_indicator_view.dart`](diffhunk://#diff-eace6e04830bd303f3388f9a72fd03c6ebb1972299428d1751f9a687a84ed53cR1-R203): Added `AITypingIndicatorView` and `AnimatedDots` widgets to display AI typing indicators with animated dots.
* [`packages/stream_chat_flutter/lib/src/ai_assistant/stream_typewriter_builder.dart`](d …
> feat(ui): AI components

- melos.yaml
- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/example/pubspec.yaml
- packages/stream_chat_flutter/pubspec.yaml
- packages/stream_chat_localizations/CHANGELOG.md
- packages/stream_chat_localizations/example/pubspec.yaml
- packages/stream_chat_localizations/pubspec.yaml
This pull request includes several updates to the `stream_chat_flutter` package and its dependencies to version `9.2.0+1`. 
Changelog updates:
* [`packages/stream_chat_flutter/CHANGELOG.md`](diffhunk://#diff-739738ae3e48428d9cb405ab14bc8a9b64c9faa943305d6a15c9d6f7810b6b04R1-R4): Added a new entry for version `9.2.0+1` to document the removal of untracked files from the package.
* [`packages/stream_chat_localizations/CHANGELOG.md`](diffhunk://#diff-7e5a4478875893a4041b2736fe9e5da05d5e6acca9e6c35746f4f832b33a8409L3-R3): Updated the changelog to reflect the new `stream_chat_flutter` dependency version `9.2.0+1`.
> fix(ui, localization): remove untracked files from stream_chat_flutter

- packages/stream_chat_flutter/lib/src/ai_assistant/ai_typing_indicator_view.dart
- packages/stream_chat_flutter/lib/src/attachment/builder/file_attachment_builder.dart
- packages/stream_chat_flutter/lib/src/attachment/builder/mixed_attachment_builder.dart
- packages/stream_chat_flutter/lib/src/attachment/builder/url_attachment_builder.dart
- packages/stream_chat_flutter/lib/src/attachment/url_attachment.dart
- packages/stream_chat_flutter/lib/src/context_menu_items/context_menu_reaction_picker.dart
- packages/stream_chat_flutter/lib/src/message_input/audio_recorder/stream_audio_recorder.dart
- packages/stream_chat_flutter/lib/src/message_input/quoted_message_widget.dart
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
- packages/stream_chat_flutter/lib/src/message_widget/reactions/reaction_picker.dart
- packages/stream_chat_flutter/lib/src/misc/flex_grid.dart
- packages/stream_chat_flutter/lib/src/poll/interactor/poll_footer.dart
- packages/stream_chat_flutter/lib/src/poll/interactor/poll_options_list_view.dart
- packages/stream_chat_flutter/lib/src/poll/interactor/stream_poll_interactor.dart
- packages/stream_chat_flutter/lib/src/poll/stream_poll_option_votes_dialog.dart
- packages/stream_chat_flutter/lib/src/poll/stream_poll_results_dialog.dart
- packages/stream_chat_flutter/lib/src/scroll_view/thread_scroll_view/stream_thread_list_tile.dart
This pull request makes several changes to the `packages/stream_chat_flutter` library to improve the layout and spacing of various widgets by replacing the `insertBetween` method with the `spacing` property. Additionally, it removes some unused imports. The most important changes include updates to the `AnimatedDots`, `FileAttachmentBuilder`, `MixedAttachmentBuilder`, `UrlAttachmentBuilder`, `StreamUrlAttachment`, and several other classes to use the `spacing` property.
* [`packages/stream_chat_flutter/lib/src/ai_assistant/ai_typing_indicator_view.dart`](diffhunk://#diff-eace6e04830bd303f3388f9a72fd03c6ebb1972299428d1751f9a687a84ed53cR115): Added `spacing` property to `Row` in `AnimatedDots` class and removed `insertBetween` method. …
> refactor(ui): use row/column spacing instead of `insertBetween`.

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
> fix(llc): fix muted channel's unreadCount incorrectly updated

- sample_app/android/gradle.properties
- sample_app/lib/app.dart
Cherry-pick notification changes [commit](https://github.com/GetStream/flutter-samples/commit/f5a493c47336910b3932a0e32fab8c867bfddf7e) from the sample app.
> feat(repo): display new PN messages

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/core/models/message.dart
- packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart
- packages/stream_chat_persistence/lib/src/db/drift_chat_database.g.dart
- packages/stream_chat_persistence/lib/src/entity/messages.dart
Fix https://github.com/GetStream/stream-chat-flutter/issues/1775 and https://github.com/GetStream/stream-chat-flutter/issues/1987
> fix(llc): fix incorrect message order

- packages/stream_chat/CHANGELOG.md
- packages/stream_chat/lib/src/client/channel.dart
- packages/stream_chat/lib/src/core/util/extension.dart
Fixes: #2171
This pull request fixed a dynamic TypeError on Flutter Web.
> fix(llc): fix [Flutter Web] TypeError JSArray

- packages/stream_chat_flutter/lib/src/misc/empty_widget.dart
> refactor(ui): convert empty widget into stateless widget

- melos.yaml
- packages/stream_chat_flutter/lib/src/attachment/handler/stream_attachment_handler_html.dart
- packages/stream_chat_flutter/lib/src/attachment/handler/stream_attachment_handler_io.dart
- packages/stream_chat_flutter/pubspec.yaml
This pull request updates the version constraints for the `file_picker` and `record` dependencies.
> chore(ui): bump file_picker and record deps

- packages/stream_chat_flutter/CHANGELOG.md
- packages/stream_chat_flutter/lib/src/message_input/stream_message_input.dart
- packages/stream_chat_flutter/lib/src/message_widget/quoted_message.dart
- packages/stream_chat_flutter/lib/stream_chat_flutter.dart
> feat(ui): Export StreamQuotedMessageWidget

- .github/workflows/beta_version_analyze.yml
Linear: FLU-152
Github Issue: #
This adds a tag for Sahil in the slack notification
> chore(repo): added Sahil to the slack notification
